### ISSUE TITLE
invalid header field value "Bearer ...

### ISSUE THREAD

**Issue by ndarilek** [hetznercloud/cli#102]
Fresh CLI install as of 5 minutes ago, using Go 1.9.3. Getting the above error, showing a bearer token, for any command I type.

I'm a new customer. Not sure if this means I pasted my token incorrectly or something else.

Thanks.

**Comment by thcyron** [comment]
Please make sure the token you pasted does not contain any newlines or other special trailing characters.

**Comment by ndarilek** [comment]
Pretty sure I triple-checked the key before pasting. Where can I find
the locally-saved key to look?

Thanks.

**Comment by ndarilek** [comment]
OK, never mind, ran `strace` on the binary and found it. There was indeed a stray unicode character in the token that somehow found its way in. Removing that from the config file solved it. Thanks!
