### ISSUE TITLE
Signed commits/tags/tarballs

### ISSUE THREAD

**Issue by shibumi** [hetznercloud/cli#120]
Hello,
I am the maintainer of the arch linux package. It would be super nice if you could sign your commits/tags and your tarballs via GPG for reliable secure releases.

How you do this is explained here:

https://help.github.com/articles/signing-commits-using-gpg/
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

tarballs are not so important for me. I would be happy with signed commits and tags.

**Comment by shibumi** [comment]
Hi,
Any update in this direction? It would be really nice to have releases that are provable secure.

**Comment by LKaemmerling** [comment]
We are currently working on overhauling the release process for the hcloud cli.  With the next release, we will have signed binaries, releases and archives.

**Comment by shibumi** [comment]
@LKaemmerling can we leave this open, until you fixed this?
