### ISSUE TITLE
Strange IDs

### ISSUE THREAD

**Issue by MindHunter86** [hetznercloud/cli#121]
Hello,
Have some strange server IDs after typing **hcloud server list**

root@centos-2gb-hel1-1 conf.d # hcloud server list | awk '{print $1,$3,$6}' | column -t
ID            STATUS   DATACENTER
959298        running  hel1-dc2
959539        running  fsn1-dc14
983857        running  nbg1-dc3
983858        running  fsn1-dc14
983859        running  hel1-dc2
1.006964e+06  off      fsn1-dc14
1.006965e+06  off      nbg1-dc3
1.006967e+06  running  fsn1-dc14

Is my failure or is it really a bug?

**Comment by LKDevelopment** [comment]
Hello,

this is a bug on our side. We are working on it!

Thank you!
