### ISSUE TITLE
Keep API keys on system's keyring

### ISSUE THREAD

**Issue by patope** [hetznercloud/cli#150]
API keys are stored as plain text in `~/.config/hcloud/cli.toml` file. This leaves keys open anyone how can gain access to user's account. Better solution (not a perfect, but better) is to store API keys in system's secure store.
  I'm using `aws-vault` command to keep my AWS keys in Linux's secret service. aws-vault uses https://github.com/99designs/keyring to abstract access system's secure store.

**Comment by thcyron** [comment]
On macOS we could use the Keychain.

**Comment by tlrh314** [comment]
Is there any update here? 

It seems that the default behaviour of `hcloud context create <name>` is still to store credentials in plain text in `~/.config/hcloud/cli.toml`. This is not clearly stated in the README or in the API documentation at https://docs.hetzner.cloud/.  It could be useful for this repository to add a line in the README to caution users that this is the case?

Moreover, it could be useful to update the API documentation too, and it would be even more neat to implement the context in such a way that no passwords have to be stored in plain text.
