### ISSUE TITLE
Unable to build 1.10.0

### ISSUE THREAD

**Issue by mphilipps** [hetznercloud/cli#153]
hi,
I was able to build 1.9.1 just fine and from looking at the dependencies in go.mod/go.sum nothing has changed there.

The error I get is:

```
# github.com/hetznercloud/cli/cli
cli/server_create.go:75:50: result.NextActions undefined (type hcloud.ServerCreateResult has no field or method NextActions)
cli/volume_create.go:77:50: result.NextActions undefined (type hcloud.VolumeCreateResult has no field or method NextActions)
```

I am kind of clueless when it comes to go, so I am unsure on where ServerCreateResult is defined. Looking at 047d465 the only new dependency seems to be on fmt, for printf.

**Comment by LKaemmerling** [comment]
Hey,

with the latest release the hcloud-go was also updated to v1.11.0, which introduced the new NextActions. You can see the change here: https://github.com/hetznercloud/cli/commit/047d46504d9827d8c4267a92b773914a975e9675#diff-37aff102a57d3d7b797f152915a6dc16L8

Please make sure, you have the latest dependencies when building the cli.

**Comment by mphilipps** [comment]
I see, my bad! I somehow thought hcloud-cli and hcloud-go  were the same and was just slightly confused by why it would list it self in that file. It is compiling just fine now.
