### ISSUE TITLE
How to create a server does not start after

### ISSUE THREAD

**Issue by xiahuaijia** [hetznercloud/cli#155]
After creating the server I need to mount the volume first, then start the system.

`hcloud server create --image <ID> --location 2 --name TEST --ssh-key <SSH Key ID> --start-after-create false --type cx21`
`hcloud: unknown command "false" for "hcloud server create"`

I removed it --start-after-create

`hcloud server create --image <ID> --location 2 --name TEST --ssh-key <SSH Key ID> --type cx21`
`1m30s[====================================================================] 100%`
`Waiting for server <server ID> to have started... done`
`Server <server ID> created`
`IPv4: xxx.xxx.xxx.xxx`

It started after the server was created

What should I do to mount the volume disk and then boot the system?

**Comment by LKaemmerling** [comment]
Currently there is no way doing this with the cli.

I'll work on a PR with support for this.

**Comment by LKaemmerling** [comment]
Sorry I misread your question.

With
``bash
hcloud server create --image <ID> --location 2 --name TEST --ssh-key <SSH Key ID> --start-after-create=false --type cx21
``
It should work, please look at the `=` between "create" and "false".

**Comment by xiahuaijia** [comment]
Thank you, the problem is solved.
