### ISSUE TITLE
Unable to authenticat

### ISSUE THREAD

**Issue by heibie** [hetznercloud/cli#159]
Hello,
I followed the Getting started and entered my API-Token. But when trying "hcloud server-type list" i get the message "hcloud: unable to authenticate your token (unauthorized)".

the entrie in ~/.config/hcloud/cli.toml seems correct (API-Token and name of Project). Do have an idea, how to solve this?

**Comment by LKaemmerling** [comment]
Please make sure, that your API Token is correct.

How long is your API Token? It should be 64 chars long.

**Comment by heibie** [comment]
Hi,
My Api-Token is only 32 characters long. can't find a longer api token in my backend.

best regards
heiko

**Comment by LKaemmerling** [comment]
You see the complete token only once, when it was created. The string (labeled with Prefix) you see in the Cloud Console is only the first 32 chars of the API Token (Prefix).

I will open an issue internally to make this more visible in our Frontend.

**Comment by heibie** [comment]
Hi,
Thank you. That was exactly the problem. I created a new Key and it worked.
