### ISSUE TITLE
SSH Host key management

### ISSUE THREAD

**Issue by joto** [hetznercloud/cli#172]
I realize this might not be the best place to raise this issue because it is not only about the hcloud command, but I don't know of a better place.

Most servers probably need SSH keys and those keys need to end up in some client configurations so you can actually ssh into the machines. At the moment this is somewhat difficult with the Hetzner cloud. There are two options I know of:

1. Let new servers create their own keys. Use `ssh` or `ssh-keyscan` to get the public keys. This is insecure, because I don't have a trusted way of accessing those keys.
2. Create the host keys myself and use the cloud-init config to put the private keys on new servers and put the public ones in my `known_hosts` files. This is inconvenient and also means I have the private keys somewhere else than the server they belong on.

Both these options work and I have written scripts to handle them. But there could be a much easier option with a little help from the Hetzner API. Some mechanism behind the scenes is alreay creating the host keys for new servers. If I could access to the public host keys through the API, I would have a trusted path to access this information and could easily use it. I am thinking of an `hcloud server create-known-hosts SERVER` command that would create a file in the ssh `known_hosts` format for SERVER with the right IP address (and possibly name) in it and the public key. Would be great if you could consider adding something like this to the API/hcloud.

**Comment by LKaemmerling** [comment]
The keys are created/generated on the first boot of the server. As we don't have access to the servers we can not provide the keys.  I guess using cloud init or ssh-keyscan would be the best solution.
