### ISSUE TITLE
Add Server show 

### ISSUE THREAD

**Issue by pr0vieh** [hetznercloud/cli#179]
Hi

i try to find the IP of an Server any way to do this easily?
expect something like hcloud server list -name string name -ip string ip ...
or add a new command like server show $string and try to find any match in the output of server list

greets Pr0vieH

**Comment by LKaemmerling** [comment]
Hey, this is already possible with Gotemplates and the describe command.

You can use:
```
hcloud server describe {serverName} -o format={{.PublicNet.IPv4.IP}}
```

which will respond only with the IPv4 Address.

**Comment by pr0vieh** [comment]
❤️ 
this tool need more doc  !
more examples usw.
but thank you very much 😎
