### ISSUE TITLE
unable to build from source manually (HEAD/master)

### ISSUE THREAD

**Issue by shinenelson** [hetznercloud/cli#183]
I am trying to build and install the client manually and I'm stuck with an `unknown import path` error : 
```
package github.com/hetznercloud/cli: unknown import path "github.com/hetznercloud/cli": cannot find module providing package github.com/hetznercloud/cli
```

This is a fresh clone of the repository and download of the dependencies.

Steps to Reproduce : 
* `git clone git@github.com:hetznercloud/cli`
* `go build`
fails with error
* `go install`
fails with error

**Comment by LKaemmerling** [comment]
Hey,

which go version do you have installed? Have you set the environment variable `GO111MODULES=on` ?

**Comment by shinenelson** [comment]
```
go version
go version go1.12.5 linux/amd64
```

The situation is the same with or without `GO111MODULES=on`. I even tried turning `GO111MODULES=off`. All the same.

**Comment by LKaemmerling** [comment]
ah, sorry. You need to make sure that the path is in your GOPATH. The normal steps:
1. `go get -u github.com/hetznercloud/cli/cmd/hcloud` (https://github.com/hetznercloud/cli#build-manually)
2. `cd $GOPATH/src/github.com/hetznercloud/cli`
3. `go build -o hcloud ./cmd/hcloud` (https://github.com/hetznercloud/cli/blob/master/script/build.bash)

**Comment by shinenelson** [comment]
oh, so I need to install `cmd/hcloud` first. I think that was what I didn't do.

I tried `go install cmd/hcloud` and it completed successfully without any errors / issues. I also have an `hcloud` binary in my `$GOPATH/bin`. (I haven't tried authenticating with a credential yet though)

Now, I'm confused as to what the `cli` part does. Is it really necessary to build again with `build.bash`? The script kind of just rebuilds the package, renames it to a more os, architecture-friendly name and puts it in `/dist`. All of that seems useful for a release manager and not for someone just trying to build the CLI just to run the `hcloud` command.

Or have I understood something wrong? Is there something significantly different about `cmd` and `cli`?

**Comment by shinenelson** [comment]
wait, my bad. It was just directory semantics. I didn't notice `cli` didn't have a `main.go` and that main.go was in `cmd/hcloud`.

I also noticed that you're importing `hetznercloud/cli/cli` into `cmd/hcloud/main.go` as well.

May I ask why is there such a structure _different_ than the rest of the modules that are built by the community?
Why couldn't you just place all of the files in the same directory and either put main.go in the root of the repository ( so that it is buildable directly from there ) or within the same directory as the rest of the files so that you wouldn't have to go through this complicated build steps.
