### ISSUE TITLE
server update function showing no updates

### ISSUE THREAD

**Issue by Askotion** [hetznercloud/cli#184]
Hey,

i've tried updating my servers using the server update function. Sadly it always says "no updates" even tho there are updates ready. 
Am i doing something wrong?

$ hcloud server update myservername
hcloud: no updates

**Comment by LKaemmerling** [comment]
You will need to specify the parameter which you want to update, like:
```bash
hcloud server update myservername --name mynewservername
```

But i guess you plan to update the OS on the server or am i wrong?
If so, this is something you can not do with the hcloud-cli. You need to access your server via SSH and takes the steps for updating your OS on the server.

```bash
hcloud server ssh myservername
```
will open a ssh connection to your server.
