### ISSUE TITLE
how do context work?

### ISSUE THREAD

**Issue by bastianh** [hetznercloud/cli#187]
I have created two contexts in my account and I can switch them with the cli.
I started a server in each of the contexts but when I do `hcloud server list` it lists both server no matter which context I currently use. There seems to be no difference.
Is a server somehow bound to a context? How are contexts used? Is there a way to see it in the cloud web interface?

**Comment by LKaemmerling** [comment]
You can see `context` as a different word for an API token. It only makes sense to have one context (API Token for the CLI) per project, I guess you have different API Tokens for the same project?

**Comment by bastianh** [comment]
Yes.. I don't understand it because you always need an api token anyways? couldn't it then show the project name ? 
For what do you create a context if only the api key matters?

**Comment by LKaemmerling** [comment]
We have no way to determine the project name from an API token, so you must specify it manually. If you have more different projects you need to have different contexts.
