### ISSUE TITLE
Volume should allow specifying where to mount

### ISSUE THREAD

**Issue by rightaway** [hetznercloud/cli#197]
Creating volumes has an `automount` option but we should be able to specify a path where to mount the device. It will greatly help with provisioning new servers if it can already be mounted on a certain point on the device when initially created.

**Comment by thcyron** [comment]
Since mounting is done by the operating system and we do not have access to the OS, we unfortunately cannot add this — admittedly useful — feature.

**Comment by rightaway** [comment]
`automount` doesn't need access to the OS?

**Comment by castarco** [comment]
> Since mounting is done by the operating system and we do not have access to the OS, we unfortunately cannot add this — admittedly useful — feature.

@thcyron I'm not sure I follow. I've seen videos on Youtube showing how the Hetzner automount feature has the result of creating mount points with very well structured names... as if Hetzner _could_ access that information (paths such as `/mnt/HC_Volume_12345678`)
