### ISSUE TITLE
hcloud server ssh should use currently logged in user by default

### ISSUE THREAD

**Issue by rightaway** [hetznercloud/cli#198]
`hcloud server ssh`, just like the regular `ssh` command, should use the currently logged in user by default. It's surprising when you're used to `ssh` and use it all the time that `hcloud server ssh` behaves differently.

Most people will only be logging in as the current default of `root` when setting things up, and the rest of the time will use an unprivileged user as that's the best practice. It's common that the user locally is the same as the user on the server, hence the default behavior of regular `ssh` command.

**Comment by thcyron** [comment]
This is by design. We want this scenario to just work:

    hcloud server create --name test --ssk-key my-key ...
    hcloud server ssh test

We inject the SSH key to the root user, so `hcloud server ssh` needs to default to root.
