### ISSUE TITLE
Get volume sizes without units

### ISSUE THREAD

**Issue by C0br4** [hetznercloud/cli#200]
I would like to see a possibility to get the size of my volumes without units that are hardcoded as "GB' anyways. Of course it can be done in other ways but there is an option to omit the header so this feels kind of inconsistent.

On a totally unrelated sidenote, installing hcloud on Gentoo pulls in almost 700mb of dependencies. Is there a binary package planned for portage or should I take the initiative?

**Comment by thcyron** [comment]
When describing a single volume, you can do:

    hcloud volume describe my-volume -o 'format={{.Size}}' 

To get the raw size number in GB. There’s no way to do the same for the list command though.

The Gentoo package is maintained by a community member, not by us. If you want to provide a binary package for Gentoo, feel free to do so.
