### ISSUE TITLE
Specify a different identity to ssh

### ISSUE THREAD

**Issue by cmoulliard** [hetznercloud/cli#208]
## Issue

If we use a different private/public key to create the Hetzner VM, then we can't ssh to this VM using this command as it will ask about a password

```
hcloud server ssh halkyon
root@116.203.87.224's password:
```

We should have the option to pass a parameter to specify the identity to be used as we can do with a ssh command
```
IP_HETZNER=$(hcloud server describe $VM_NAME  -o json | jq -r .public_net.ipv4.ip)
ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_hetzner_snowdrop root@$IP_HETZNER
Last failed login: Tue Oct  1 11:17:12 CEST 2019 from 183.111.104.121 on ssh:notty
There was 1 failed login attempt since the last successful login.
Last login: Tue Oct  1 11:16:46 2019 from ip-62-235-26-205.dsl.scarlet.be
[root@halkyon ~]#
```

**Comment by LKaemmerling** [comment]
We don't want to add more `ssh` options to the `hcloud server ssh` command, so we will add a new command `hcloud server ip` which will respond with just the IP, so you can to it easily without using jq or json here. 

Tracked as #214
