### ISSUE TITLE
Accept ssh options

### ISSUE THREAD

**Issue by alexanderkjeldaas** [hetznercloud/cli#211]
Related to #113, the option `-oStrictHostKeyChecking=no` is important to support as it is required in order to gather the server ssh key on the first connection.

WIth a "correctly"/modern configured ssh, it won't be possible to script any commands without this option, or the equivalent.

**Comment by LKaemmerling** [comment]
Mmh, it won't make sense that we add all ssh parameters to `hcloud server ssh`. 

We have decided to add a new command `hcloud server ip` which will respond only with the IP, so you can build your ssh command on your own like:

```sh
ssh -l foo -p 1234 -o oStrictHostKeyChecking=no $(hcloud server ip server.example.com) uptime
```

**Comment by LKaemmerling** [comment]
Will be tracked as #214
