### ISSUE TITLE
Server list as JSON

### ISSUE THREAD

**Issue by andir** [hetznercloud/cli#222]
It would be nice if we could get a `hcloud server list -o json,column=name,ipv6` so we can work with the data using `jq` or python or similar… Parsing the table stable format is feasible but not really as nice to integrate in other scripts around managing a server.

**Comment by LKaemmerling** [comment]
If you want to use python we would recommend using our python SDK: https://github.com/hetznercloud/hcloud-python

We will think about adding json output to the list commands.

**Comment by andir** [comment]
Just another data point why I didn't just jump on the python SDK: To use that SDK you'll have to reinvent the entire secret handling. it would be really nice if the CLI and the library would be able to share credentials by default. Similar to how `gcloud` and the `aws` tooling works.
