### ISSUE TITLE
server-list json: Missing server labels...

### ISSUE THREAD

**Issue by seimic** [hetznercloud/cli#230]
Hi,

tested the new release 16.1 a little bit and found something.

The regular list command outputs labels if specified in columns list

`hcloud server list -o colum ns=id,labels`

Output is something like this
```
ID     LABELS
123456 label1=value1, label2=value2
123457 label1=value1
123458 
```
In the json version all labels in the server list are null. 
```
{
  ...
  "labels": null
}
```
Labels on images/snapshots within the server block are present.
Labels on networks and volumes are OK too (I mean hcloud network list -o json and hcloud volume list -o json)

I hope this helps.

Kind regards,
Michael

**Comment by LKaemmerling** [comment]
Fix for this was merged into master with #231
