### ISSUE TITLE
Iso list returns bogus null values for deprecation for json output.

### ISSUE THREAD

**Issue by fahrradflucht** [hetznercloud/cli#232]
The json output for `hcloud iso list` returns Go null-value timestamps for `deprecated` instead of `null` as the API does. - This is probably not intended.

**Example:**
```
➜ hcloud iso list -o json | jq '.[1].deprecated'
"0001-01-01T00:00:00Z"
```

**Comment by LKaemmerling** [comment]
I don't see an easy way how we could fix that. We try to use the same schema as within the API (and therefore use the hcloud-go schema package (https://github.com/hetznercloud/hcloud-go/blob/master/hcloud/schema/iso.go#L11)). Sadly changing this to allow null values would be a breaking change. We will look into this when we can make breaking changes in the hcloud-go. I will close this issue, as we can not fix this bug atm, but also atm you won't get deprecated ISOs through the API.
