### ISSUE TITLE
Add prices for server list

### ISSUE THREAD

**Issue by eike-fokken** [hetznercloud/cli#241]
Hello there,

it would be nice if the cli tool could also list the monthly prices for servers in server-type list.

**Comment by LKaemmerling** [comment]
I personally don't see a big benefit from this, as the price can be different in different locations. The CLI output should be as easily readable as possible. I will talk to our other team members about this. Thank you!

**Comment by eike-fokken** [comment]
If I understand you correctly, this means that prices from my cli output and prices from the cli output of someone living elsewhere are not comparable.
I wouldn't mind that at all, as I would like this feature so I can see the price the instant before I order the server.
Of course I can check in the web ui but that is much more clumsy (and error prone) than double-checking the price by just typing another command.

**Comment by LKaemmerling** [comment]
Showing this information in the list view would make it a bit overlookable. With the next CLI release the pricings will be shown
 in the describe command like here:
 <img width="476" alt="Bildschirmfoto 2020-07-17 um 11 37 14" src="https://user-images.githubusercontent.com/4281581/87772330-e0d8c500-c821-11ea-97c9-18b0ee1aa7d3.png">

**Comment by eike-fokken** [comment]
Not my favourite but close enough! Looking forward to it!
