### ISSUE TITLE
Improve install instructions with go

### ISSUE THREAD

**Issue by bluepuma77** [hetznercloud/cli#243]
I installed go and ran the installer `go get -u github.com/hetznercloud/cli/cmd/hcloud`.

But there was no output, I don't know what it did and if/where it was installed.

```
root@haproxy1:~# wget https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz
...
root@haproxy1:~# tar -C /usr/local -xzf go1.14.4.linux-amd64.tar.gz
root@haproxy1:~# export PATH=$PATH:/usr/local/go/bin
root@haproxy1:~# go get -u github.com/hetznercloud/cli/cmd/hcloud
root@haproxy1:~# hcloud
-bash: hcloud: command not found
```

It would be great if you could add some info, maybe mention where is was installed.

Tested on Debian 10 with go1.14.4.linux-amd64.tar.gz

**Comment by LKaemmerling** [comment]
We recommend using our prebuild binaries: https://github.com/hetznercloud/cli/releases
