### ISSUE TITLE
Insecure first ssh access

### ISSUE THREAD

**Issue by hadmut** [hetznercloud/cli#246]
Hi, 
when using hcloud server ssh NAME for the first time, the ssh server key is not yet known/confirmed, and the user has no simple way to verify the server's public key other than using the Hetzner Cloud console to login (which contradicts this tool if manual interaction is needed) or using special cloud-init functionality not avalable for all linux flavors. 

I am aware that this is a problem of the Hetzner API and not this tool, but I don't see where to submit bug reports for the API, and maybe, someone in charge for the API listens here.

**Comment by LKaemmerling** [comment]
Hello @hadmut, 

could you please open a Support Ticket for this? I personally think there wont' be a way to make these, other than having a "custom script" running on each server that sends the host key to our API "back". This violates our principle that we want to avoid having software on the servers that is not needed for them to work.  An option would be using a custom image with functionality that sends the host key after the first boot to a secure storage. 

Actually there is no way how we could achieve this.  If you have further questions, please ask our operation guys via a support ticket. Thank you!
