### ISSUE TITLE
hcloud was not built properly

### ISSUE THREAD

**Issue by hadmut** [hetznercloud/cli#247]
The README says

If you have Go installed, you can build and install the `hcloud` program with:

    go get -u github.com/hetznercloud/cli/cmd/hcloud

and indeed, I get a running hcloud. But  hcloud version says

% hcloud version
hcloud was not built properly

**Comment by LKaemmerling** [comment]
This is expected. The version is set on build time (and the string `hcloud was not built properly` is the default: https://github.com/hetznercloud/cli/blob/master/cli/version.go#L10). 

We always recommend using prebuild binaries (https://github.com/hetznercloud/cli/releases).
