### ISSUE TITLE
Output configuration

### ISSUE THREAD

**Issue by thcyron** [hetznercloud/cli#25]
We want to be able to control how output is formatted.

For example, we want to disable printing the column names (first line) to be able to do things like:

```
$ hcloud server list | wc -l
5
```

Or to specify which columns are printed:

```
$ hcloud server list
ID
1
2
3
```

In the future we might also want to support other output formats (JSON, YAML).

## Proposal

Output is completely controlled via the `-o` option which can be specified multiple times with different values. A value is either just a key `key` or a key-value pair `key=value`.

### Examples

To disable printing column names:

```
$ hcloud -o nocolumns server list
```

To only print the ID and name columns and sort by name:

```
$ hcloud -o columns=id,name -o sort=name:desc server list
```

To output JSON:

```
$ hcloud -o format=json server list
```

The option `format=table` is the default output format.

**Comment by thetechnick** [comment]
I would prefer `noheader` instead of `nocolumns`, because there are still columns being printed, otherwise OK

Will the column names correspond to the json schema, or to the `hcloud` lib field names?

**Comment by thcyron** [comment]
Yep, `noheader` is a way better name.
