### ISSUE TITLE
Deleting snapshot?

### ISSUE THREAD

**Issue by nosecam** [hetznercloud/cli#250]
More a question than an issue...
I am using scheduler on windows to automatically creating snapshots 

e.g.:
set HCLOUD_TOKEN=xxxxx
hcloud server create-image --type "snapshot" yyyyyyyy
unset HCLOUD_TOKEN

I would like to delete snapshots after a certain period of time. But it looks like there is no "delete-image"? Also "older-than" would be helpful :-)
Best

**Comment by LKaemmerling** [comment]
You can delete images with `hcloud image delete <ID>`
