### ISSUE TITLE
Server creation /w --network [after network creation] fails

### ISSUE THREAD

**Issue by tlrh314** [hetznercloud/cli#255]
I am trying to create 1 network, 2 servers, 1 volume for a [tutorial on how to mount the cloud volume on multiple servers /w sshfs](https://github.com/hetzneronline/community-content/pull/250) via the hcloud cli. However, server creation (`cx11` with `debian-10`) fails when using the `--network` flag, and manual boot of the server then refuses to `ifup ens10` when configuring the network [manually](https://wiki.hetzner.de/index.php/Cloud_Networks_Configuration/en#Manual_configuration_via_DHCP). 

**Steps to reproduce**
```bash
hcloud ssh-key create --public-key-from-file=~/.ssh/hcloud_sshfs_rsa --name my-ssh-key

hcloud network create --name network --ip-range 10.0.0.0/24
hcloud network add-subnet network --type server --network-zone eu-central --ip-range 10.0.0.0/28

hcloud server create --ssh-key my-ssh-key --location nbg1 --type cx11 --image debian-10 --network network --name server1
```
**Observed behavior**
```bash
SSH key 1782171 created
Network 121882 created
1s [=====================================] 100.00%
Subnet added to network 121882
3s [=====================================] 100.00%
Waiting for server 6782567 to have started
... failed
hcloud: canceled (canceled)
```

**Expected behavior**
I expect the server to start, attach to the network, have a network interface for the private network, and be assigned the internal ip via `dhcp` that is set in the network (in this case `10.0.0.2`).

**Possible workaround**
```bash
hcloud ssh-key create --public-key-from-file=~/.ssh/hcloud_sshfs_rsa --name my-ssh-key

hcloud network create --name network --ip-range 10.0.0.0/24
hcloud network add-subnet network --type server --network-zone eu-central --ip-range 10.0.0.0/28

hcloud server create --location nbg1 --ssh-key my-ssh-key --type cx11 --image debian-10 --name server1
hcloud server create --location nbg1 --ssh-key my-ssh-key --type cx11 --image debian-10 --name server2
hcloud server attach-to-network server1 --network network --ip 10.0.0.2
hcloud server attach-to-network server2 --network network --ip 10.0.0.3
```

**Observed behavior for the workaround**
```bash
SSH key 1782162 created
Network 121880 created
1s [=====================================] 100.00%
Subnet added to network 121880
3s [=====================================] 100.00%
Waiting for server 6782534 to have started
 ... done
Server 6782534 created
IPv4: 116.203.43.57
2s [=====================================] 100.00%
Waiting for server 6782540 to have started
 ... done
Server 6782540 created
IPv4: 78.47.36.207
0s [=====================================] 100.00%
Server 6782534 attached to network 121880
1s [=====================================] 100.00%
Server 6782540 attached to network 121880
7s [=====================================] 100.00%
Waiting for volume 6332078 to have been attached to server 6782534
 ... done
Volume 6332078 created
```

**System**
- System Version:	macOS 10.15.5 (19F101)
- Kernel Version:	Darwin 19.5.0
- hcloud v1.17.0
- Homebrew 2.4.7
- `hcloud` is installed via `brew install hcloud`
- My project limit is recently increased from 10 to 20 servers and this is server 11. Not sure if relevant.

**Comment by LKaemmerling** [comment]
It should work now. There was a small problem on our side.

**Comment by tlrh314** [comment]
Amazing, thanks @LKaemmerling for the quick fix! I can confirm that server creation and provisioning now works on my end.
