### ISSUE TITLE
--selector -l not matching results

### ISSUE THREAD

**Issue by wingsuitist** [hetznercloud/cli#257]
The following list commands using the -l / --selector option do not deliver any results, despite having a matching result when running it without the selector.

```sh
hcloud floating-ip list -l TYPE=ipv4

hcloud server list -l name=master-1
hcloud server list -l 'name in (master-1)'

hcloud server list --selector name=master-1
```

**Comment by LKaemmerling** [comment]
@wingsuitist do the resources have that label? We don't set any label automatically (like the name or the type).

**Comment by wingsuitist** [comment]
@LKaemmerling good point, I think I confused it with the --field-selector from kubectl.
