### ISSUE TITLE
How to use enable-protection?

### ISSUE THREAD

**Issue by tlrh314** [hetznercloud/cli#261]
While trying to protect a network, volume, servers, loadbalancer through the `hcloud` cli interface I was not quite able to figure out how to use the `enable-protection` method in a timely manner by looking at the README, the API documentation, the code, the help method, and the issues of this repository. It might be useful to add a few lines on how to do so in the README, but for those searching issues to figure it out:

-  `hcloud network enable-protection <NAME> delete`
-  `hcloud server enable-protection <NAME> delete rebuild`
-  `hcloud volume enable-protection <NAME> delete`
-  `hcloud load-balancer enable-protection <NAME> delete`

seems to do the trick.

**Comment by LKaemmerling** [comment]
We plan to overhaul the autocompletion and help texts of all of our CLI commands. The specific values always described in the API (under `protection` of the specific resource).

**Comment by delaskoff** [comment]
Hi @LKaemmerling 
Can you please provide the link to that API?
The only place I could find a description of how to enable protection for servers is this issue (and more than 4 years have passed already)

**Comment by jooola** [comment]
@delaskoff Here is a link to the relevant API call to change a server protection https://docs.hetzner.cloud/#server-actions-change-server-protection
