### ISSUE TITLE
Unable to use hcloud with ZSH

### ISSUE THREAD

**Issue by DataRepository** [hetznercloud/cli#275]
I've been able to install hcloud with Go but can't get 'hcloud' to work on ZSH.

I can run ./hcloud while inside the folder but cannot use 'hcloud'. In fact, I have to place the period in ./hcloud completion zsh > ~/.config/hcloud/completion/zsh/_hcloud for it to 'work'. Any tips?

**Comment by LKaemmerling** [comment]
Did you placed the binary into your path? What happens if you run ‘which hcloud’?

**Comment by DataRepository** [comment]
![hcloud](https://user-images.githubusercontent.com/12666951/93148794-afc72480-f6ec-11ea-9650-0f72038cc33c.png)
I unfortunately am trying to load the completions on ZSH to no avail.

'which hcloud' gives me the following message: hcloud not found

**Comment by LKaemmerling** [comment]
Then the hcloud binary is not within your PATH. Therefore you need to run it locally `./hcloud` or move the binary to a folder from your path (as a sample: `mv hcloud /usr/local/bin/hcloud` (assuming `/user/local/bin` is within your PATH which it is on most OSs)

**Comment by Virg1l** [comment]
That makes perfect sense and worked perfectly. Thank you so much!

**Comment by DataRepository** [comment]
That did the trick! Thanks a bunch <3
