### ISSUE TITLE
hcloud volume format

### ISSUE THREAD

**Issue by schamane** [hetznercloud/cli#276]
I have an feature request.
It would be great to have posibility to rebuild volumes (like its can be done with servers) to cleanup volume.
Or also to format volume to switch between ext4 or xfs.

```bash
hcloud volume rebuild --format=xfs 739990
```

or

```bash
hcloud volume format --format=ext4 739000
```

Reask about if someone is sure, all data will be lost.

```bash
hcloud volume rebuild --format=ext4 --yes 739000
```

**Comment by LKaemmerling** [comment]
You can do that easily from within a server, so having this on an API layer wouldn't be a big benefit. You are ways more flexible when doing all the actions on the server. You must see, that the volumes are after creating a big "blackbox" for us. We can expand them, but nothing more :)

**Comment by LKaemmerling** [comment]
Won't fix (or implement) this as is `on-host`.
