### ISSUE TITLE
Transfer server

### ISSUE THREAD

**Issue by martinvonwittich** [hetznercloud/cli#277]
Currently, it doesn't seem to be possible to transfer servers via `hcloud`. As the [API docs](https://docs.hetzner.cloud/) also don't mention a transfer API, I assume there isn't one? Would it be possible to implement it?

I currently have to transfer 10-20 servers per week, and having to do it manually over the web interface does get a bit annoying :D

**Comment by LKaemmerling** [comment]
This is only possible through the Cloud Console, as the Cloud Console has access to the specific user that is calling. The Integrations only have the possibility to access one project.
