### ISSUE TITLE
run command async without foreground

### ISSUE THREAD

**Issue by omerh** [hetznercloud/cli#284]
Hi,

Just trying out the cli tool, I was wondering if there is an option to run it without `--poll-interval` ?
I want to run a snapshot script and I don't need to see the progress of the snapshot creation.

I tough of `--poll-interval -1` or something

**Comment by LKaemmerling** [comment]
Currently, there is no way to disable the progress bar at the moment. 

Do i understand it correctly, that you just want to disable the progress bar, but the command should still wait until the snapshot is created?

Specifying the poll-interval should only be used when you run into the rate limit.

**Comment by omerh** [comment]
Hi,
Not exactly, I don't want to see the progress and don't want to wait until its finished.
Just send an async request for snapshot 

I've made this https://github.com/omerh/hetzner-hcloud-snapshots and I don't need to wait till its done

**Comment by LKaemmerling** [comment]
But then you will never know if the snapshot is ready (useable) or not?

**Comment by omerh** [comment]
Im counting on Hetzner to succeed in snapshot (like I do in AWS and DO) 
If it may break than you can leave it and close the issue 👍

**Comment by ktomk** [comment]
For me with hcloud cli it works pretty well redirecting stdout to /dev/null - this effectively removes the progress-bar.

Stderr is untouched as I normally want to see the errors (could be misconfiguration / changes as well), when unattended all output is also turned into a notification, so I only want the errors.

Can imagine that to prevent the output of the progress bar and run in background in your script could do:
~~~
hcloud server create-image --type snapshot --label id=$1 \
     --description server-$1 --poll-interval 0 $1 >/dev/null &
                                                  ########## #
~~~

Is this what you're looking for?

**Comment by omerh** [comment]
Yes. But buitin the command and not directing to `/dev/null`

**Comment by LKaemmerling** [comment]
I would still recommend directing it to `/dev/null`. Your "use case" is really limited, and you should always expect that there might be a problem or something else and then react to it.  Therefore i think given people such an option would confuse them more than it would help them.
