### ISSUE TITLE
server labels in listing undefined order

### ISSUE THREAD

**Issue by ktomk** [hetznercloud/cli#285]
no idea if this is considered an issue in the REST API, experiencing it with the `hcloud` utility:

me has two labels on one server, when using

~~~
$ hcloud server list -o columns=labels
LABELS

foo=bar, baz=boo
~~~

But then it can also output
~~~
baz=boo, foo=bar
~~~

when tracking changes on the output repeatedly, diffs are triggered albeit there was no change. this increases the noise to signal ratio.

would be great to increase the stability. for me it would be fine to sort by label name (binary), but most likely the standard golang collation and string normalization routines should suffice as well.

as written already, no idea if this makes sense within the API response. Me merely sees it as a display issue, but if the label sort order is declared undefined in the REST API already, it appears to be a valid option to change it there without any backward / forward compatibility breaks - me has to admit to not have looked into the REST API so far, so this is a bit of a guessing game.

**Comment by LKaemmerling** [comment]
Labels are just values attached to a server, they are ordered as you added them. I don't think that we should sort them on the API side (even not in CLI).

**Comment by ktomk** [comment]
@LKaemmerling Yes, if they would be in the order they were added, would be fine too for me. But that is not the case. They switch back and forth while the setup is untouched.

**Comment by ktomk** [comment]
@LKaemmerling: After looking into the source code it fell like scales from my eyes: 

The order in a map is undefined in Golang. This is the solution.

Please find a pull-request that stabilizes the order:

**Comment by ktomk** [comment]
Could you consider to reopen the issue for going on with the fix? @LKaemmerling

**Comment by LKaemmerling** [comment]
@ktomk i just merged your fix. It will be within the next release.
