### ISSUE TITLE
hcloud server change-type can hang indefinetly

### ISSUE THREAD

**Issue by martinvonwittich** [hetznercloud/cli#288]
I've been rescaling about ~800 servers yesterday and today, and I have encountered an issue where `hcloud server change-type` (and possible also `hcloud server shutdown`, not sure) will sometimes just hang seemingly indefintely:

```
hcloud server change-type <name> cx31
```

```
Shutting down <name>                                                                     
3s [=====================================] 100.00%                                                                         
Server 6682637 shut down                                     
Waiting for <name> (attempt 1/120)...                                                    
Waiting for <name> (attempt 2/120)...                                                    
Rescaling <name> from cx21 to cx31                                                       
55m0s [___________________________________] 0.00%                                                                         
```

(The `Waiting for` and `Rescaling` messages are from my shell script, the rest should be `hcloud` output)

Currently, I have to cycle through all my screens and have to look out for `hcloud` processes that have been working for longer than 30 minutes to manually check if the action has been completed :/

In this case, the web interface confirms that the rescaling has long been completed:

https://console.hetzner.cloud/projects/381235/servers/6682637/overview

> Server Typ geändert zu CX31 vor einer Stunde

The server has been online for 52 minutes at this point:

```
<name> ~ # uptime
 22:20:26 up 52 min,  1 user,  load average: 0,04, 0,09, 0,08
```

I now have to kill the `hcloud` instance with `kill` manually so that my script can continue to the next server.

I've attached the file created by `sudo timeout 10 strace -tt -p 46968 -f -o hcloud.log`, in case this might be useful: [hcloud.log](https://github.com/hetznercloud/cli/files/5533370/hcloud.log)

**Comment by martinvonwittich** [comment]
According to my history, I killed 15 `hcloud` instances yesterday, while rescaling ~500 servers (2 `hcloud` commands per server - `hcloud server shutdown` and `hcloud server change-type`).

**Comment by martinvonwittich** [comment]
> and possible also `hcloud server shutdown`, not sure

OK, I can now also definitely confirm that `shutdown` is affected too:

```
Shutting down <name2>                                                                         
32m5s [____________________________________] 0.00%                                                                         
```

https://console.hetzner.cloud/projects/381235/servers/5140450/overview

> Server heruntergefahren vor 33 Minuten

[hcloud-shutdown.log](https://github.com/hetznercloud/cli/files/5533399/hcloud-shutdown.log)

**Comment by LKaemmerling** [comment]
I guess you run into the rate limit, that's why the action was never "succeeded". You should spread up the load a bit over time and/or set the `--poll-interval` to something like "1m" (1 minute), so the progressbar updated it self every minute instead of every 0.5 sec (default pol interval).

**Comment by martinvonwittich** [comment]
> I guess you run into the rate limit, that's why the action was never "succeeded".

Ah, yes, that might be the reason; I remember the web interface sometimes displaying this as an error, but it did continue to work rather well for some reason, so I didn't think too much of it.

> You should spread up the load a bit over time and/or set the `--poll-interval` to something like "1m" (1 minute), so the progressbar updated it self every minute instead of every 0.5 sec (default pol interval).

Good advice. Is there something `hcloud` could do to reduce the probability of this occurring? For example, the API seems to report the remaining allowed requests (`RateLimit-Remaining` header), so `hcloud` could automatically increase the poll interval to accommodate for a shrinking limit?

At the very least, it would probably be useful to display warnings when the API responds with `429 Too Many Requests` to make the issue more obvious :)

A note in the help text for `--poll-interval` that explains that you might want to increase the interval when doing a lot of requests might also be useful.

**Comment by martinvonwittich** [comment]
I'm again suffering from this problem while rescaling ~1300 servers. This time I intentionally increased the poll interval, hoping that this would circumvent the problem:

```
hcloud server change-type --keep-disk --poll-interval 5s some-server.de cx31
```

But I'm still getting locked out by the API :(

One particular `hcloud` process has now been hanging for 59 minutes. I checked `/proc/<hcloud pid>/fd`, and I noticed that there isn't actually a socket in there:

```
martin@martin ~ % ll /proc/171723/fd
insgesamt 0
lrwx------ 1 martin martin 64 Mai 22 06:04 0 -> /dev/pts/27
lrwx------ 1 martin martin 64 Mai 22 06:04 1 -> /dev/pts/27
lrwx------ 1 martin martin 64 Mai 22 06:04 2 -> /dev/pts/27
lr-x------ 1 martin martin 64 Mai 22 06:04 3 -> /dev/tty
lrwx------ 1 martin martin 64 Mai 22 06:04 4 -> 'anon_inode:[eventpoll]'
lr-x------ 1 martin martin 64 Mai 22 06:04 5 -> 'pipe:[1437941]'
l-wx------ 1 martin martin 64 Mai 22 06:04 6 -> 'pipe:[1437941]'
```

For comparison a more recent process that isn't hanging:

```
martin@martin ~ % ll /proc/187585/fd
insgesamt 0
lrwx------ 1 martin martin 64 Mai 22 06:04 0 -> /dev/pts/16
lrwx------ 1 martin martin 64 Mai 22 06:04 1 -> /dev/pts/16
lrwx------ 1 martin martin 64 Mai 22 06:04 2 -> /dev/pts/16
lr-x------ 1 martin martin 64 Mai 22 06:04 3 -> /dev/tty
lrwx------ 1 martin martin 64 Mai 22 06:04 4 -> 'anon_inode:[eventpoll]'
lr-x------ 1 martin martin 64 Mai 22 06:04 5 -> 'pipe:[1744320]'
l-wx------ 1 martin martin 64 Mai 22 06:04 6 -> 'pipe:[1744320]'
lrwx------ 1 martin martin 64 Mai 22 06:04 7 -> 'socket:[1514085]'
```

Looks to me like `hcloud` actually loses its TCP connection to the server, but doesn't realize this and then hangs in an endless loop.
