### ISSUE TITLE
View server local IP

### ISSUE THREAD

**Issue by azatuni** [hetznercloud/cli#289]
Hi,

it would be very useful to be able to view server local IP via hcloud.

Thanks beforehand.

**Comment by LKaemmerling** [comment]
Hey @azatuni,

what do you mean by local IP? You should be able to see the Public IP and the private IP on the `hcloud describe` command. If you need a specific field you can simply use  the "-o format" output. Sample to get the Public IPv4:
```
hcloud server describe <yourserver>  -o format={{.PublicNet.IPv4.IP}}
```

For more details have a look here: https://github.com/hetznercloud/cli#output-configuration

Does this solve your problem @azatuni?

**Comment by azatuni** [comment]
Hi @LKaemmerling 

Thank you for quick response
I tried this:
`hcloud server describe <yourserver> -o format={{.PrivateNet.IP}}`
call fails, but 
`hcloud: template: :1:13: executing "" at <.PrivateNet.IP>: can't evaluate field IP in type []hcloud.ServerPrivateNet`

Also this call
`hcloud server describe <yourserver> -o format={{.PrivateNet}}`
returns 
`[{0xc000315680 <private_ip> [] 86:00:00:85:3a:19}]`
so is it possible to get pivate IP as Public or I should parse myself?

**Comment by LKaemmerling** [comment]
Hey @azatuni,

you can use the following:
```
hcloud server describe <your-server> -o format="{{ (index .PrivateNet 0).IP }}"
```

Sample for server "abc":
```
$ hcloud server describe abc -o format="{{ (index .PrivateNet 0).IP }}"
10.0.0.2
```

**Comment by azatuni** [comment]
Yeap, thanks.
