### ISSUE TITLE
'Image_Size' not uniform

### ISSUE THREAD

**Issue by omexlu** [hetznercloud/cli#291]
Hello,

Hcloud CLI does not show the same value of 'Image_size' as Hetzner-Interface.

In Hetzner-Interface 2 decimal places are displayed and CLI only one or it is rounded up.

It would be great if this would be consistent :)

Thanks in advance.

**Comment by LKaemmerling** [comment]
Hey @omexlu,

thank you! I opened up an MR to fix this :)

**Comment by omexlu** [comment]
Hi, 

Thank you, after the fix i need to redownload hcloud to my linux-desktop, right?

**Comment by LKaemmerling** [comment]
@omexlu when we released it, yes, but i don't think we will make a release with this fix only.
