### ISSUE TITLE
Permission denied for command from hcloud snap package

### ISSUE THREAD

**Issue by mashkovd** [hetznercloud/cli#296]
I installed hcloud by snap
and then i write _hcloud context create my-project_
i got _hcloud: open /home/mashkov/.config/hcloud/cli.toml: permission denied_
Why i do wrong?
thx

**Comment by 9ov7** [comment]
not resolved!!!

**Comment by jooola** [comment]
The Snap package for the hcloud CLI is really outdated and unmaintained, I recommend that you install the CLI using other methods for the time being.

The permission error might be related to snap not having access to your user home directory.

**Comment by 9ov7** [comment]
May be. I had to install via Brew and everything works.
How about adding this package to your Hetzner rep?
Or an installation method via bash?
