### ISSUE TITLE
hcloud: SSL-Handshake-Error

### ISSUE THREAD

**Issue by omexlu** [hetznercloud/cli#300]
Hallo,

Mit der Cloud-API gibt es derzeit Probleme die CLI wirft ein SSL-Handshake-Error:
hcloud: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50": net/http: TLS handshake timeout

Danke im voraus.

**Comment by LKaemmerling** [comment]
Halllo @omexlu,

vielen Dank! Wir untersuchen das Problem aktuell. Weitere Informationen gibt es hier: https://status.hetzner.com/de/incident/ae0e7eb8-e291-4bc4-a34f-23b572b07414

Ich schließe die Issue hier, da es perse kein CLI Fehler/Problem ist.

**Comment by omexlu** [comment]
Ok danke, die Status-Page hat auch ein Problem :)
Kann nicht aufgerufen werden.

**Comment by LKaemmerling** [comment]
> Ok danke, die Status-Page hat auch ein Problem :)
> Kann nicht aufgerufen werden.

@omexlu das funktioniert bei mir problemlos, was ist denn das Problem?

**Comment by omexlu** [comment]
Die Website ist nicht erreichbarVerbindung wurde zurückgesetzt.
Versuchen Sie Folgendes:

Verbindung prüfen
Proxy und Firewall prüfen
ERR_CONNECTION_RESET

**Comment by LKaemmerling** [comment]
Wie sieht ein MTR in die Richtung aus?

**Comment by omexlu** [comment]
Kann ich aktuell nicht testen, aber auch von diversen Proxys nicht zu erreichen, sodass ich ein Problem in meinem Heimnetz ausschliessen kann.

**Comment by LKaemmerling** [comment]
@omexlu ich kann die Status Seite von diversen Stellen aus problemlos erreichen (Telekom, Unitymedia, mtr.sh)

**Comment by omexlu** [comment]
Hm, komisch:
https://nl.hideproxy.me/go.php?u=69cFwyxfyO8wECDCOp6upflOG7ewIouqQN6l7ymUrOvw4ZxPNdOPTTGsZVPIym%2FyiZyNDQnNPyTYQdiW3C8GyyN1I7vrBXg%3D&b=5&f=norefer

Hide webproxy weiße Seite, ich versuchs später nochmals.
