### ISSUE TITLE
Create server from snapshot

### ISSUE THREAD

**Issue by JKamsker** [hetznercloud/cli#305]
Is it possible to create a server from a snapshot? If yes, how do i do that? I didnt find a way to accomplish that.

Thanks in advance

**Comment by LKaemmerling** [comment]
Hey @JKamsker,

You can use the `--image` flag with the ID of the snapshot.
```bash

hcloud image list

# get the ID from your snapshot

hcloud server create --name test --image <snapshotID> [..]

**Comment by JKamsker** [comment]
Ah ok, i didn't know that "hcloud image list"  shows snapshots aswell and "--image" does only accept the ids, not the names

Thanks

**Comment by LKaemmerling** [comment]
@JKamsker --image also support names, but Snapshot does not have names. Currently only images with type system (Ubuntu-20.04 as a sample) have names :)
