### ISSUE TITLE
JSON output with -o flag for all commands

### ISSUE THREAD

**Issue by binaryfire** [hetznercloud/cli#307]
Hi guys

Would it be possible to allow the **-o json**  flag to be used with all this tool's commands (for example server creation)? This is essential for using the CLI's output in scripts and automation. I'm currently using curl with the API but and was hoping to move over to the CLI for ease of use.

Right now **-o json** only works with list commands.

**Comment by Jeuners** [comment]
Json Output für "server create..." wäre schon super, da der befehl  essenziell ist. Im Moment parse ist ich die Ausagbe als List, das klappt natürlich nur so lange die Ausgabe auch gleich bleibt.

**Comment by gerritsangel** [comment]
Would also love to have JSON output for server create 👍
