### ISSUE TITLE
[Feature Request] Add support for powershell Command Line Tab Completion

### ISSUE THREAD

**Issue by JKamsker** [hetznercloud/cli#312]
Tab completion on windows would be awesome

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.1

used in for example https://github.com/microsoft/winget-cli/blob/master/doc/Completion.md?WT.mc_id=-blog-scottha

**Comment by LKaemmerling** [comment]
Hey @JKamsker,
Thank you for your Issue!

I submitted an MR to support Powershell (#316). Could you please test this MR and verify it?  You should be able to get a "developer" build here: https://github.com/hetznercloud/cli/actions/runs/721351146

**Comment by JKamsker** [comment]
Oh my god i love it ❤
Feels really nice, great work 👍
