### ISSUE TITLE
HCLOUD_TOKEN is not respected

### ISSUE THREAD

**Issue by codethief** [hetznercloud/cli#317]
The README says:

> Instead of creating a context, you can set the token via the HCLOUD_TOKEN environment variable.

This does not seem to work. After installing hcloud v1.22.1 (the binary distribution; on Ubuntu 20.04), here's what I did:

```console
$ export HCLOUD_TOKEN="foo"
$ hcloud server list
hcloud: no active context or token (see `hcloud context --help`) <-------- ?
$ hcloud context create my-context
Token: foo
$ cat ~/.config/hcloud/cli.toml | grep token
  token = "foo"  <-------- Great, now my token is stored on disk unencrypted which was exactly what I was trying to avoid.
```

**Comment by runar** [comment]
I would just like to add that the `HCLOUD_TOKEN` environment variable worked for me right now, using hcloud 1.22.1 manually downloaded (not built or from Homebrew) on macOS:

```shell
$ export HCLOUD_TOKEN="token"

$ hcloud server list
ID         NAME                         STATUS    IPV4             IPV6                      DATACENTER
# actual servers
```

**Comment by kartikdc** [comment]
I installed hcloud via apt on Ubuntu 20.04 and it respect the environment variable for me.

**Comment by codethief** [comment]
@runar @kartikdc Following your comments, I have tried to reproduce the issue again but it's now working for me, too. Very weird, I have no idea what I did differently last time.

Anyway, I'll close this for the time being.
