### ISSUE TITLE
[feature request] scp

### ISSUE THREAD

**Issue by Hvitgar** [hetznercloud/cli#318]
I would really appreciate a `hcloud server scp` command =)

**Comment by eppjohnny** [comment]
I don't think that this kind of feature would be possible to develop.

Hetzner provides you servers and you have to manage/configure/securing the (ssh) connection to the server.

The hcloud-cli tool can't guess your server connection configuration, if you provide your credentials, you could also use the scp command alone.

This might work if hetzer would implement some kind of backdoor, that the cli tool is able to directly connect into your machine.

**Comment by Hvitgar** [comment]
I don't understand - since hcloud server ssh exists, why would hcloud server scp not be possible? Configuration like ports has to be given via command line for hcloud server ssh too, its just a convenient way to deal with ip abstraction by using the hcloud server name instead

**Comment by eppjohnny** [comment]
Oh sorry, now I understand the additional value of using Scp in combination with hcloud. 

IMHO leaving an entry in your .ssh/config file would also help a lot, but wouldn‘t solve the Problem with the IP abstraction.

**Comment by LKaemmerling** [comment]
Hey @Hvitgar,

implementing an SCP command into the hcloud go is nothing we want to do/support. The CLI should be as slim as possible and not a full-featured DevOps tool to manage a server. We have a few smaller commands like `hcloud server ssh` to make the start with fresh servers easier.
