### ISSUE TITLE
More columns in `hcloud server list -o columns=...` (especially for traffic monitoring)

### ISSUE THREAD

**Issue by miluxmilux** [hetznercloud/cli#319]
Hi there!
Is there a reason why I can't get `outgoing_traffic`, `ingoing_traffic` or `included_traffic` from the columns in `hcloud server list -o columns=...`?
Would you take a look at a PR if I provided one?

Cheers

**Comment by LKaemmerling** [comment]
Hey @miluxmilux,

this was added in #325 and will be included in the next release.
