### ISSUE TITLE
Feature Request: Hetzner DNS 

### ISSUE THREAD

**Issue by eppjohnny** [hetznercloud/cli#321]
Hello there,

I'm using Hetzner about a year now and also switched my DNS nameservers to Hetzner DNS.

I also found an API documentation about Hetzner DNS (https://dns.hetzner.com/api-docs/).

Because of that, I thought that maybe the CLI tool would also support managing DNS,  but I can't find anything regarding DNS.

Are there any plans in integrating DNS into the hcloud CLI?

**Comment by LKaemmerling** [comment]
Hey @eppjohnny,

the DNS API is not Part of the Hetzner Cloud product. Therefore there are no plans to integrate the DNS API into the hcloud CLI.
