### ISSUE TITLE
[Feature] Implement a command that updates a firewall rule with the user ip address

### ISSUE THREAD

**Issue by nicolasvac** [hetznercloud/cli#326]
As in title,

it would be nice if the CLI could allow us to dinamically update a single firewall rule (via firewall rule ID) to allow everything from only the current public ip of the machine running the command (like every dyndns software acts).

The command should delete the older ip address and update with the new one.
I imagine you cannot guarantee which one was the older ip, so the main logic should be to delete all existing ips in the rule everytime and only add the new one.

Thats why i think the command should prompt a required confirmation.

Es: `hcloud firewalls dyn-update <firewall_rule_id>`
This one should prompt to input "yes" for confirmation.

Es: `hcloud firewalls dyn-update <firewall_rule_id> --yes`
This one should execute the command directly.

The reason to have a firewall_rule_id is to not have to attach / detach a new / old firewall rule every update from all the servers, making this troublesome.

I'm asking to implement it because it would be nice if this could all be done inside the hcloud CLI, instead of relying on custom implementations or even external programs which will require your hcloud token.

Thank you.

**Comment by LKaemmerling** [comment]
Hey @nicolasvac,

we discussed your request in the team and decided to not implement something like this. The reason is quite simple, the CLI should be a tool that allows you to build more specific stuff. Also there is a lot of effort that needs to be implemented in such a command and the "more technical" reason: We do not have a direct "rule" id, so you would always need to specify the old IP too to remove it from the firewall, that's not possible. 

We think that your request is quite easily doable with our `hcloud firewall replace-rules` command, where you replace all rules for this specific firewall. We recommend having a dedicated firewall for this (a server can have multiple firewalls assigned).

**Comment by LKaemmerling** [comment]
@nicolasvac  this is already what replace-rules is doing, it replaces all rules of a firewall with the new rules you provide. 

So basically you just need to build something to generate the correct rules format (json) and then call replace-rules with this file. 

As I said the CLI should be as generic as possible, so we don't want to introduce such commands as you suggested.

**Comment by nicolasvac** [comment]
@LKaemmerling I wrote this simple script as you suggested.

Do you think it could be useful in the examples section of the repo ?

```sh
if [ -n "$1" ]; then
  echo "Firewall rule specified. Starting the script."
else
  echo "Firewall rule not specified. Exiting."
  exit
fi

PUBLIC_IP=$(curl "https://www.ipinfo.io/ip")

if [ -z ${PUBLIC_IP+x} ]; then
  echo "Unable to get the public ip of this machine. Exiting."
  exit
else
  echo "$PUBLIC_IP"

  cat >hcloud_dyn.json <<EOF
[
  {
    "direction": "in",
    "source_ips": [
      "!USERIP!/32"
    ],
    "destination_ips": [],
    "protocol": "*",
    "port": "*"
  },
]
EOF

  sed -i "s/!USERIP!/$PUBLIC_IP/" hcloud_dyn.json

  hcloud firewall replace-rules "$1" --rules-file "hcloud_dyn.json"
fi
```

Thanks.

**Comment by LKaemmerling** [comment]
hey @nicolasvac,

cool script! I would suggest you putting it into a github repo and make it available for everyone. We could then add it to our awesome list.

I guess your overall issue is solved with this, therefore I would like to close the issue. If you still have questions feel free to reopen the issue or create a new one.
