### ISSUE TITLE
Switching from one project to another project in hcloud

### ISSUE THREAD

**Issue by farooqbabajan1540** [hetznercloud/cli#330]
I have created multiple projects in hetzner cloud with different api tokens of respective projects.
While creating the new servers through command line, i was not able to switch to the other project.
I couldn't find any command to switch between project.
Kindly help me to fix this.

**Comment by farooqbabajan1540** [comment]
ex: 
hcloud context list
ACTIVE   NAME
         farooq
*        devops
 here i want to switch from devops to farooq project.

**Comment by LKaemmerling** [comment]
Hey @farooqbabajan1540,

you can use the `hcloud context use <context-name>` command for switching between your contexts.

**Comment by farooqbabajan1540** [comment]
> hcloud context use

thanks @LKaemmerling , it's working as expected.
