### ISSUE TITLE
Don't require ssh keys if given in cloudinit

### ISSUE THREAD

**Issue by rightaway** [hetznercloud/cli#332]
If you don't provide ssh keys as part of the api command then the server is created with a root password. But you can provide ssh keys as part of cloudinit instead of in the api, which is better to remain compatible with other cloud providers. You shouldn't have to provide it in both places to prevent generating a root password, it should be enough just in cloudinit.

The api should parse the cloudinit config provided and see if there's a top level `ssh_keys` key provided, and if so don't generate a root password. (Or we should at least be able to pass a parameter when creating a server to tell it not to generate a root password, but not having to pass this is better.)

**Comment by LKaemmerling** [comment]
Hey @rightaway,

thank you for your request. I passed the request to our team. As this repo is only for the hcloud cli and your request is API specific I will close it here.

**Comment by rightaway** [comment]
@LKaemmerling Where can we file issues about the API? And track progress? These kinds of requests get forgotten otherwise.

**Comment by LKaemmerling** [comment]
@rightaway we don't have a Public roadmap or something like this. The request won't be missed :) as I said I passed it to the team and they put it on the wishes list.
