### ISSUE TITLE
Termux: connection refused

### ISSUE THREAD

**Issue by Poldi1977** [hetznercloud/cli#341]
Hi

I use `hcloud` on Android with Termux App.

I added the API-Key with `hcloud context create` command.

```
$ hcloud server list
hcloud: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50": dial tcp: lookup api.hetzner.cloud on [::1]:53: read udp [::1]:43000->[::1]:53: read: connection refused
```
Whats going wrong?

**Comment by LKaemmerling** [comment]
Hey @Poldi1977,

looks like your DNS server is not reachable.

And the hetzner cloud API does not have a IPv6 Address (DNS AAAA Record) you can reach the Cloud API currently only over APIv4.
