### ISSUE TITLE
Apply Firewall to LoadBalancer

### ISSUE THREAD

**Issue by malikkirchner** [hetznercloud/cli#342]
We use a CDN, i.e. Cloudflare, in front of a Hetzner LB. It would be great, if we could restrict incoming traffic to a list of source IP-ranges (e.g. https://www.cloudflare.com/ips-v4). Is there any plan to allow IP filter rules in the cloud firewalls and to also apply them to the cloud LBs?

**Comment by malikkirchner** [comment]
Is a `loadBalancerSourceRange` annotation described in https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/218 the better approach?

**Comment by LKaemmerling** [comment]
Hey @malikkirchner,

i added a +1 to our Feature Wish List for this request.  I will close the issue here, as this repo is for the CLI and your request is a generic feature request.

**Comment by malikkirchner** [comment]
Hi @LKaemmerling, thank you!
