### ISSUE TITLE
Appended 'null' output when listing servers with json-output

### ISSUE THREAD

**Issue by ojnny** [hetznercloud/cli#343]
Hi!

When I run: 
hcloud server list -o json

I get an extra 'null' in the output at the end, like this:
[{"id":7898793,"name":"redis","status":"running", etc ...}]
null

hcloud version 1.24.0

Is it a bug or is it me doing something wrong? Any help appreciated!

**Comment by TomSDEVSN** [comment]
See #345

**Comment by LKaemmerling** [comment]
Will be fixed with the currently in progress release v1.15.1
