### ISSUE TITLE
JSON unmarshall error on Ubuntu 20.x

### ISSUE THREAD

**Issue by robertorubioguardia** [hetznercloud/cli#358]
Hi,
I am getting this when running `hcloud sever list`, no matter how I install the CLI tool. I have tried the binary file, deb package and building with go.

`hcloud: json: cannot unmarshal number into Go struct field Price.servers.server_type.prices.price_hourly.net of type string`

Works fine on Mac though. Thanks for that.

Cheers.

**Comment by LKaemmerling** [comment]
Hey @robertorubioguardia,

this will be fixed in a couple of minutes (from API side so nothing to do for you here).

**Comment by robertorubioguardia** [comment]
Thanks a lot for the quick response. I confirm that all is working now.

**Comment by LKaemmerling** [comment]
Okay great, then i will close the issue.
