### ISSUE TITLE
Feature request - Backups

### ISSUE THREAD

**Issue by robertorubioguardia** [hetznercloud/cli#359]
Hi guys,

It would be nice if `hcloud server create` included a flag to enable backups.

Cheers.

**Comment by LKaemmerling** [comment]
Hey @robertorubioguardia,

we want to keep the `create` call as small as possible to not overload the users with many options.

You can easily do the same in one line:
```
hcloud server create --name my-server --type cx11 --image ubuntu-20.04 && hcloud server enable-backup my-server
