### ISSUE TITLE
Panic when listing in JSON format

### ISSUE THREAD

**Issue by opax** [hetznercloud/cli#360]
Some list subcommands panic with the option `json`:

* `hcloud iso list -o json` panics with `interface conversion: interface {} is *hcloud.ISO, not hcloud.ISO`
* `hcloud location list -o json` panics with `interface conversion: interface {} is *hcloud.Location, not hcloud.Location`

Version: hcloud v1.28.0
Platform: macos

**Comment by LKaemmerling** [comment]
Hey @opax,

thank you for the report! I submitted a fix with #361. When this MR was reviewed we will issue a Bugfix release.

**Comment by opax** [comment]
That's great to hear, thank you for the quick reaction!
