### ISSUE TITLE
New release create, but no binary attached

### ISSUE THREAD

**Issue by ctron** [hetznercloud/cli#366]
I just ran into the issue that our GitHub actions runner machine did not get terminated, because the `hlcoud` binary could not be found.

We are using the https://github.com/3bit/setup-hcloud to install the `hcloud` binary in our GitHub actions workflow. This action checks for the most recent version, and downloads it.

During the release of the 1.29.0 version of `hcloud`, a new release was created, but not binary attached. This made the `setup-hcloud` action fail, and the server kept running.

A workaround can be the configure a specific version for the `setup-hcloud` binary. But I also think that in this repository, no new release, without release artifacts, should be created in a "non-draft" state.

**Comment by LKaemmerling** [comment]
Hey @ctron,

we currently have issues with the CI/CD pipeline. The binaries will be attached soon, we need to build it locally.

**Comment by ctron** [comment]
@LKaemmerling Thanks for the feedback! I really sympathize!

Maybe consider running GitHub actions on @hetznercloud, works like a charm :grin:
