### ISSUE TITLE
hcloud server create with --user-data-from-file fails with hcloud: unknown shorthand flag: 'u' in -u

### ISSUE THREAD

**Issue by andycockerill-cpi** [hetznercloud/cli#371]
Hi,

I'm trying to create a server with the  --user-data-from-file option.

The file looks like:

```
#cloud-config
        runcmd:
          - cd "$RUNNER_HOME"
          - instance_id="\$(cat /var/lib/cloud/data/instance-id)""
          - sudo -u "$RUNNER_USER" ./config.sh --unattended $extra_flags --name "\$instance_id" --url "https://github.com/$GH_REPO" --token "$runner_token" --labels "$instance_id"
          - ./svc.sh install "$RUNNER_USER"
          - ./svc.sh start
```
hcloud exits with: hcloud: unknown shorthand flag: 'u' in -u

It looks like it's picking up the "-u" is "sudo -u" as an option that it can't understand.
Any ideas how I can workaround this?

**Comment by fhofherr** [comment]
Hi,

this does not look like an issue with the cli but with your cloud config file. As such I'm closing the issue.

Two things that I find suspicious about your file:

1. The indentation looks off. That may be an issue with copy and pasting it to github, but it may be still worth checking.
2. Where do you set the `RUNNER_HOME` and `RUNNER_USER` environment variables.

Another thing you can try out is creating a instance using exactly the same distro as in the case with the failing cloud-config and trying it out manually. Maybe this helps solving the issue.
