### ISSUE TITLE
Feature request: Provide official cli Docker image

### ISSUE THREAD

**Issue by hegerdes** [hetznercloud/cli#372]
To enable easy usage of the cli on any host it would be great if you would provide an official Docker image on Dockerhub.

This allows the usage of the cli in CI systems and without the need to permanently install something to the host.

*Feel free to close this if you don't support this use case*

**Comment by LKaemmerling** [comment]
Hey @hegerdes,

we would prefer to keep the currently available build options. This said if you want you could distribute it via a docker image on your own, similar to what we already have for other Third-Party Users: https://github.com/hetznercloud/cli#third-party-packages
