### ISSUE TITLE
image/snapshot list sorting

### ISSUE THREAD

**Issue by rbeier** [hetznercloud/cli#373]
Hi, 

at first: thank you for the excellent cli. Much fun to work with!

It would be really nice if you could add a flag for sorting the image (snapshot) list. When automating server creation i want to get the ID of the most recent snapshot.

```
hcloud image list -t snapshot -o noheader -o columns=id
```

Thanks a lot.

**Comment by LKaemmerling** [comment]
Hey @rbeier,

sorry for the rather late reply, we were quite busy. I just opened up an MR to add support for sorting all of our resources:
https://github.com/hetznercloud/cli/pull/390
