### ISSUE TITLE
Tokens stored plaintext

### ISSUE THREAD

**Issue by AndiDog** [hetznercloud/cli#377]
`~/.config/hcloud/cli.toml` stores unencrypted access tokens for the Hetzner API. At best, the CLI would use the system keychain where available. It could be implemented flexibly with a "credential process", see e.g. [awskeyring and the awscli credential_process config](https://github.com/servian/awskeyring).

**Comment by Wulfheart** [comment]
Dunno why this has ben marked as stale as it is a quite serious issue.
