### ISSUE TITLE
Release v1.29.1 lacks binaries

### ISSUE THREAD

**Issue by languitar** [hetznercloud/cli#383]
It seems the v1.29.1 release here on Github lacks binaries. All previous releases have binaries attached. Is that intended?

**Comment by LKaemmerling** [comment]
Hey @languitar,

sadly we had issues with the apple Notarization service yesterday. You can find the binary now under the correct release: https://github.com/hetznercloud/cli/releases/tag/v1.29.4

I'm sorry that this might be caused trouble!
