### ISSUE TITLE
How to block inbound traffic of a server in hetzner using hcloud

### ISSUE THREAD

**Issue by cbncb1** [hetznercloud/cli#386]

**Comment by tagirb** [comment]
There are Hetzner firewalls for this purpose:
https://docs.hetzner.com/cloud/firewalls/faq/

Here is the respective `hcloud` Terraform resource:
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/firewall

**Comment by LKaemmerling** [comment]
Hey @cbncb1,
as @tagirb already wrote you can use our Firewall feature for this. Thanks @tagirb for answering this already :)
