### ISSUE TITLE
hcloud cli ssh key option

### ISSUE THREAD

**Issue by s4ke** [hetznercloud/cli#394]
I only see support for hcloud server ssh <server> with ssh keys, It would be great for automation if we could supply more details like the SSH identity.

**Comment by s4ke** [comment]
I didn't find a way to specify the identity file, is this possible with the existing setup already?

**Comment by LKaemmerling** [comment]
Hey @s4ke,

the `hcloud server ssh` command was just built for simplicity. We assume there that everyone has his environment configured to "access" those servers directly. If you want to specify another identity or ssh key we recommend so use ssh directly. Just as a sample you can use `hcloud server ip <serverid-or-name>` to get the IPv4 (or `hcloud server ip -6 <serverid-or-name>` to get the IPv6) and then shell this out to the ssh command: 
```
ssh root@$(hcloud server ip <server-id-or-name>)
```
