### ISSUE TITLE
hcloud server ssh doesn't seem to work properly if server has no IPv4

### ISSUE THREAD

**Issue by svenstaro** [hetznercloud/cli#395]
So I made a server without an IPv4:
```
❯ hcloud server list                                                                                                                              
ID         NAME              STATUS    IPV4   IPV6                      PRIVATE NET            DATACENTER
21880363   testserver   running   -      2a01:4f8:abcd:abcd::/64    10.0.0.12 (test)   nbg1-dc3
```
This fails: (it works when the server has an IPv4)
```
❯ hcloud server ssh testserver
ssh: Could not resolve hostname <nil>: Name or service not known
```
This works: (I just chose a random IPv6 of the subnet)
```
❯ ssh 2a01:4f8:abcd:abcd::1
```
I believe this is an oversight in the CLI following the release of primary IPs.

**Comment by ciearius** [comment]
Hello! Does applying the `--ipv6` option fix it? @svenstaro

**Comment by svenstaro** [comment]
@LKaemmerling I'd prefer if it picked a suitable public IP by default even if `--ipv6` is not provided. If people want to force a specific protocol, they should use `--ipv4` or `--ipv6`. Otherwise, `hcloud server ssh` should just try to do the right thing pick IPv6 if available and then try IPv4 if it is not.

**Comment by ciearius** [comment]
I agree with @svenstaro. The default behaviour should be to choose the "best available".

**Comment by svenstaro** [comment]
@LKaemmerling What do you think about my suggestion? I think we shouldn't treat IPv6 as a second-class citizen here.

**Comment by LKaemmerling** [comment]
Hey @svenstaro,

i just opened an MR to achieve this :) https://github.com/hetznercloud/cli/pull/406
