### ISSUE TITLE
hcloud firewall create --rules-file ... errors out: "hcloud: json: cannot unmarshal object into Go value of type []schema.FirewallRule"

### ISSUE THREAD

**Issue by ootada** [hetznercloud/cli#399]
The command errors out given its own cli json or web api json output (even with the default firewall rules). 
Should not be the case.

**Comment by LKaemmerling** [comment]
Hey @ootada,

could you please give us more details as a sample: Which json structure did you use? There are no "default firewall rules".

**Comment by ootada** [comment]
Right, how do you call the rules that are automatically given when creating a new firewall in Web UI? I call it default rules:

`
{"applied_to":[],"created":"2022-07-27T14:54:05.917317+00:00","id":473510,"labels":{},"name":"firewall-test","rules":[{"description":null,"destination_ips":[],"direction":"in","port":"22","protocol":"tcp","source_ips":["0.0.0.0/0","::/0"]},{"description":null,"destination_ips":[],"direction":"in","port":null,"protocol":"icmp","source_ips":["0.0.0.0/0","::/0"]}]}
`

p.s. Doing manual curl to API with same JSON works ok.

**Comment by LKaemmerling** [comment]
The Frontend does this to make the usage easier. The CLI does not have any defaults, so you need to specify the rules you would like to have (similar to terraform, ansible etc.)

**Comment by ootada** [comment]
So I want to clone firewall. I dump the JSON from existing firewall, in this case (for example) its a default Web UI rules. I give this JSON to "hcloud firewall create", as outlined in manual. Result: error.

hcloud binary version 1.30.1 linux-amd64

**Comment by KarimJedda** [comment]
I had the same error here. 

```

hcloud firewall describe firewall-1 -o json > current_firewall.json

hcloud firewall replace-rules firewall-1 --rules-file="current_firewall.json"

hcloud: json: cannot unmarshal object into Go value of type []schema.FirewallRule

```

**Comment by LKaemmerling** [comment]
@KarimJedda in your sample you get the json result of the whole firewall. This is not only the rules.

```
hcloud firewall describe firewall-1 -o json | jq '.rules' > current_firewall.json
```

would work in your case.

**Comment by KarimJedda** [comment]
That is exactly what I needed! Thank you very much. 

Is there anywhere some documentation so I don't bother you in the future?

**Comment by LKaemmerling** [comment]
@KarimJedda asking question here or in our community board (https://forum.hetzner.com) is always fine :)
