### ISSUE TITLE
Same output as API

### ISSUE THREAD

**Issue by rightaway** [hetznercloud/cli#400]
This tool should have the same output as the API. https://github.com/hetznercloud/cli/issues/307 got closed by the bot.

@LKaemmerling

**Comment by LKaemmerling** [comment]
Adding support for this is not trivial. Also, it is for all List calls nearly impossible (in the current Datastate of the CLI). We are aware that this is not ideal, however changing this is a significant effort that is currently not possible for us. We recommend using either the hcloud-go directly or curl.
