### ISSUE TITLE
SIGSEGV on server list

### ISSUE THREAD

**Issue by hhoechtl** [hetznercloud/cli#404]
hcloud server list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e55a6]

goroutine 1 [running]:
net.networkNumberAndMask(0x0, 0x4, 0xc0002be080, 0x48327c, 0xc000100800, 0x0, 0x0)
	net/ip.go:476 +0x26

**Comment by LKaemmerling** [comment]
Hey @hhoechtl,

which hcloud-cli version do you use? Do you also use servers with our flexible network feature?

**Comment by hhoechtl** [comment]
I did `go install github.com/hetznercloud/cli/cmd/hcloud@latest` but when I enter `hcloud version` I get `hcloud was not built properly`.

I'm not sure what the flexible network feature is. All our servers have a public IPv4 and IPv6 and are attached to one private network.

**Comment by LKaemmerling** [comment]
@hhoechtl we don't recommend installing the cli this way :) we always recommend using our prebuilt binaries.  

Can you by chance give me the full stack trace? The part above is not complete :)

**Comment by hhoechtl** [comment]
Sure:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e55a6]

goroutine 1 [running]:
net.networkNumberAndMask(0x0, 0x4, 0xc000458240, 0x48327c, 0xc2ad00, 0x0, 0x0)
	net/ip.go:476 +0x26
net.(*IPNet).String(0x0, 0xc000463a50, 0xc0000a6820)
	net/ip.go:526 +0x45
github.com/hetznercloud/cli/cli.describeServerListTableOutput.func2(0x871280, 0xc0001f4840, 0x91fb5b, 0x4)
	github.com/hetznercloud/cli/cli/server_list.go:79 +0x45
github.com/hetznercloud/cli/cli.(*tableOutput).Write(0xc000405ad0, 0xc0000fbc88, 0x6, 0x6, 0x871280, 0xc0001f4840)
	github.com/hetznercloud/cli/cli/output.go:265 +0x2e5
github.com/hetznercloud/cli/cli.runServerList(0xc0000ebc70, 0xc00019ab00, 0xc5b0f8, 0x0, 0x0, 0x0, 0x0)
	github.com/hetznercloud/cli/cli/server_list.go:64 +0x3ea
github.com/hetznercloud/cli/cli.(*CLI).wrap.func1(0xc00019ab00, 0xc5b0f8, 0x0, 0x0, 0x0, 0x0)
	github.com/hetznercloud/cli/cli/cli.go:118 +0x56
github.com/spf13/cobra.(*Command).execute(0xc00019ab00, 0xc0000201a0, 0x0, 0x0, 0xc00019ab00, 0xc0000201a0)
	github.com/spf13/cobra/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d2580, 0x0, 0x0, 0xc0001bf6c0)
	github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra/command.go:895
main.main()
	github.com/hetznercloud/cli/cmd/hcloud/main.go:35 +0x65
```

**Comment by LKaemmerling** [comment]
Yep you have a really old version running :) Please update to the lastest version (all the parts in the stack trace are no longer there). `go install` shouldn't be used anymore :)
