### ISSUE TITLE
load-balancer call returns non zero result occasionally

### ISSUE THREAD

**Issue by amaddio** [hetznercloud/cli#411]
I am using version 1.30.1 of the cli. We use the following command to remove a cloud server from a load balancer:

```sh
hcloud load-balancer remove-target mega-apply-web --server 12345678
```

This has worked in the past. Since most recently, it succeeds only erratically returning a non zero status with the following error message:

```hcloud: Get "https://api.hetzner.cloud/v1/load_balancers?name=<name-of-webserver>": read tcp 10.36.65.142:47892->213.239.246.1:443: read: connection reset by peer```

Can someone tell me what is causing the issue?

**Comment by tomsiewert** [comment]
This sounds more like an API issue. Does this issue still occur for you?

**Comment by amaddio** [comment]
Hey @tomsiewert. The problems have not occured in the last days. Looking good. I'll close the issue.

I agree that it probably sounds as it were an API issue. Would be happy for a link to create an issue in the right place in case the error starts occuring again. Thanks.

**Comment by apricote** [comment]
In case it happens again you can just reopen this issue. It would be great if you could include debug logs of a failed called, that would make it easier for us to pinpoint the issue.

For debug logs run with `HCLOUD_DEBUG=true hcloud load-balancer ...`.

If you feel uncomfortable posting the debug log here, you can also send it to me via email: `julian.toelle at hetzner-cloud.de`

**Comment by amaddio** [comment]
Thanks @apricote. Will do. I'd post the log and replace any sensitive information.
