### ISSUE TITLE
how to use create-image for a backup?

### ISSUE THREAD

**Issue by pcace** [hetznercloud/cli#438]
Hi there, 

i am having a hard time to figure out how to use the create-image functionality. i am trying this: 

`hcloud server create-image --type backup`
but it fails with this: 

`hcloud: accepts 1 arg(s), received 0`

but the manual sais: 

```
 hcloud server create-image --help
Create an image from a server

Usage:
  hcloud server create-image [FLAGS] SERVER

Flags:
      --description string     Image description
  -h, --help                   help for create-image
      --label stringToString   User-defined labels ('key=value') (can be specified multiple times) (default [])
      --type string            Image type (required)

Global Flags:
      --poll-interval duration   Interval at which to poll information, for example action progress (default 500ms)
```

wich clearly sais:   `    --type string            Image type (required)`

so what am i doing wrong here?

**Comment by apricote** [comment]
Hey @pcace,

it looks like you are missing the `SERVER` argument, which can be the ID or name of the server.

**Comment by pcace** [comment]
oh no! thats embarrassing :/ 
i just missed that. Sorry. It totally works! Thanks!

**Comment by apricote** [comment]
No problem! The error message could certainly be improved.
