### ISSUE TITLE
bash completion seems to be broken

### ISSUE THREAD

**Issue by mszmurlo** [hetznercloud/cli#462]
Hi,

I just downloaded `hcloud-linux-386.tar.gz` (the only version for linux) from the [releases repository](https://github.com/hetznercloud/cli/releases). As explained in the README, I did `source <(hcloud completion bash)` to get shell completion with `bash`. 

Whenever I hit TAB for a completion I get an error. For example:
```
maurycy@kali> hcloud serv_get_comp_words_by_ref : commande introuvable
```

where *commande introuvable* stands for *could not find the command* in french.

My OS version is:
```
maurycy@kali> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

My bash version is:
```
maurycy@kali> bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
```

Maurycy

**Comment by apricote** [comment]
> x86_64

You should be using the `hcloud-linux-amd64.tar.gz` instead. GitHub does not show all release assets by default, make sure to click "Show all 21 assets". You can also directly download it through this link: https://github.com/hetznercloud/cli/releases/download/v1.31.1/hcloud-linux-amd64.tar.gz

Please report wether it worked with the `amd64` release, or if you still have issues with the completion.

**Comment by mszmurlo** [comment]
Hi,

sorry to say that the issue is still here:

```
maurycy@kali> hcloud ver_get_comp_words_by_ref : commande introuvable
              ^^^^^^^^^^ trying to make a completion on 'version'
```

**Comment by apricote** [comment]
Weird. I am unable to reproduce it on a fresh hcloud server with ubuntu-20.04. My last remaining idea is that you may not have `bash-completion` installed locally:

```
sudo apt update
sudo apt install bash-completion
```

If that  still does not work, could you run the following commands and post the output? You can also attach a file here.

```
declare -f # lists all functions in your bash context, should include the hcloud completion funcs

type _get_comp_words_by_ref # show info about the missing func

# get full debug log from completion
set -x
hcloud ver<TAB>
set +x
```

**Comment by mszmurlo** [comment]
Hi

`bash-completion` is installed

Here is the result of `declare -f`: [declare-f.result.gz](https://github.com/hetznercloud/cli/files/11007666/declare-f.result.gz)

And here come the log from completion attempt
```
maurycy@kali> hcloud ver+ local cur prev words cword split
+ declare -A flaghash
+ declare -A aliashash
+ declare -F _init_completion
+ __hcloud_init_completion -n =
+ COMPREPLY=()
+ _get_comp_words_by_ref -n = cur prev words cword
+ '[' -x /usr/lib/command-not-found ']'
+ /usr/lib/command-not-found -- _get_comp_words_by_ref
_get_comp_words_by_ref : commande introuvable
+ return 127
+ return
```

**Comment by apricote** [comment]
`_get_comp_words_by_ref` is not available in your environment, but should be defined by `bash-completion`. It looks like your bash environment is not correctly sourcing the package.

Could you try running `source /etc/bash_completion` before executing the completion?

**Comment by mszmurlo** [comment]
Bingo! Thanks for your time and support

**Comment by mszmurlo** [comment]
Bingo! Thanks for your time and support
