### ISSUE TITLE
Allow getting JSON on server creation

### ISSUE THREAD

**Issue by shyim** [hetznercloud/cli#470]
I am bash scripting creating a Hetzner Server and getting the IP. Right now I have to do 2 steps to create and get the ip as the create command does not have an JSON output

```
hcloud server create --image docker-ce --location fsn1 --type cpx31 --name=docker-local --ssh-key 7588395
SERVER_IP=$(hcloud server describe docker-local -o json | jq .public_net.ipv4.ip -r)
```

I would rather have in create already the server ip as JSON to save the second command :)

**Comment by apricote** [comment]
Having json output from the create subcommands sounds like a good idea :)

FYI, you can also get the public ipv4 by running `hcloud server ip docker-local`
