### ISSUE TITLE
hcloud create server without publicIPv4

### ISSUE THREAD

**Issue by mabels** [hetznercloud/cli#471]
Hello,

i tried to create a server as in the console without an public ipv4 address but egress ipv4 connectivity. And this seams not to work as expected.
Either i get an public ipv4 address and egress connectivity or no ipv4. 
What are the commandline options. I tried

--without-ipv4
and
--primary-ipv4 "" 

thx in advance

meno

**Comment by apricote** [comment]
Hey @mabels,

a server can only directly access the internet if it has a public IPv4 address. If your server is only connected to a private network, you need to setup a [NAT gateway](https://community.hetzner.com/tutorials/how-to-set-up-nat-for-cloud-networks) to route the traffic from this server to internet and back.

Hope this answers your question.

**Comment by mabels** [comment]
Thx, this what i expected to happend but i "clicked" a server with the ipv4 option off and thought i had still egress ipv4 connection due to the 100.x.y.z address assignent.
