### ISSUE TITLE
Clarification: Will `hcloud server delete` imply detaching volumes, firewalls and primary IPs?

### ISSUE THREAD

**Issue by mkarg** [hetznercloud/cli#485]
I would kindly ask to *extend the documentation of hcloud* by a short clarification of the question, whether `hcloud server delete` actually implies the detaching of volumes, firewalls and primary IPs. Thanks.

**Comment by mkarg** [comment]
@apricote Julian, I would be happy if you could shed some light on this. Thanks a lot for sharing you knowledge! :-)

**Comment by McPringle** [comment]
I have the same question.

**Comment by mkarg** [comment]
@apricote Could be please briefly share some light on this? Thanks!

**Comment by apricote** [comment]
Deleting a server does detach any other attached resources. I have updated the API docs and it will go out with the next deployment.
