### ISSUE TITLE
Clarification: What does `hcloud firewall update` actually do?

### ISSUE THREAD

**Issue by mkarg** [hetznercloud/cli#486]
I wonder what "updating" a firewall actually means? What happens when this command gets issued? I would be happy if the hcloud documentation could shed some light on this.

**Comment by mkarg** [comment]
If this is the wrong place to ask such questions please point me to the right location. Thanks.

**Comment by apricote** [comment]
Hey @mkarg,

the CLI is a wrapper around our API. The docs for the CLI are currently not really informative right now, it is on our todo list to improve this.

If you have any questions about a specific subcommand, it usually help to open the API reference for this functionality: [Update a firewall](https://docs.hetzner.cloud/#firewalls-update-a-firewall). In this case, the only thing `hcloud firewall update` allows you to do is change the name, as labels are handled by the `add-label`/`remove-label` subcommands.

**Comment by mkarg** [comment]
Thank you, Julian! :-)
