### ISSUE TITLE
Improvement: hcloud server create should start server as last step, not as first step

### ISSUE THREAD

**Issue by mkarg** [hetznercloud/cli#487]
Current `hcloud server create` is performing the following sequence:
1. create server
2. **start server**
3. attach volumes
4. attach firewalls
5. attach primary IPs

As a result, there could be a racing condition between hcloud attaching resources, and the server OS using these resources (e. g. trying to use IP or volume *before* hcloud has finished attaching it).

IMHO the sequence should be changed in a way that boots up the OS in the *last* step to preven this potential risk:
1. create server
2. attach volumes
3. attach firewalls
4. attach primary IPs
5. **start server**

**Comment by mkarg** [comment]
I understand that this is an open source project, but I really wonder why the main committers not even *comment* on this proposal? 🤔 So potential contributors know *upfront* if it makes sense to file a PR, or if it will be rejected unseed because the idea itself is dumb.

**Comment by apricote** [comment]
Hey @mkarg,

where do you see that these are the actions `hcloud server create` performs? As far as I can tell in the code, we send a single request to `POST /v1/servers` to create the server with all associated resources.

(This does not include enabling the protection or backups)

**Comment by mkarg** [comment]
This is the sequence one sees on the console when runing the hcloud command (at least at time of writing the original issue).

**Comment by apricote** [comment]
Hey, I just talked to the team responsible for the endpoint, and we figured out that the actions are just returned in the wrong order in `next_actions`. If you look at the actual completion times of the individual actions (for example with `HCLOUD_DEBUG=true hcloud server create ...`) you can see that you suggested sequence is the sequence in which the actions are processed.
