### ISSUE TITLE
Enhancement: hcloud server create --enable-protection

### ISSUE THREAD

**Issue by mkarg** [hetznercloud/cli#488]
It is a bit tedious that a server can be built with a single command including all kinds of resource bindings like firewall, ip and volumes, but a second command is needed to enable protection (and backup).

It would be cool if there would be an `--enable-protection` (and `--enable-backup`) flag do that as the last task of `hcloud server create`.

**Comment by mkarg** [comment]
It would be nice if a committer could briefly comment if such a feature would make sense.

**Comment by apricote** [comment]
This sounds like a good idea! @pauhull will take a stab at the implementation.

**Comment by pauhull** [comment]
Implemented in #567, #568 and #570

**Comment by mkarg** [comment]
Thanks a lot, @pauhull ! :-)
