### ISSUE TITLE
fix: hcloud server shutdown should wait until the server is actually shut down

### ISSUE THREAD

**Issue by apricote** [hetznercloud/cli#489]
Running `hcloud server shutdown` only waits until the ACPI shutdown signal is sent to the server, not until the server is actually shut down. This can cause issues if the user is directly doing another action right after (like unassigning Primary IPs).

This is expected based on the action returned by the API.

We should poll the server to wait until it is actually marked as shutdown in the API to prevent race conditions.

**Comment by pauhull** [comment]
Implemented in #569
