### ISSUE TITLE
RFC: hcloud ssh-key list    should flag the default key

### ISSUE THREAD

**Issue by toralf** [hetznercloud/cli#509]
so that it can be used in scripts creating a new VPS.

**Comment by apricote** [comment]
Hey @toralf, the "default" SSH Keys are not a feature of the public API. They are a Cloud Console only feature.

You can read more about this decision in this comment: https://github.com/hetznercloud/cli/issues/425#issuecomment-1328946333

**Comment by toralf** [comment]
understood
