### ISSUE TITLE
Problem with missing "with_architecture", missing version(s) in brew? 

### ISSUE THREAD

**Issue by emcdng** [hetznercloud/cli#527]
Hi guys,

based on the documentation of Terraform here: [https://registry.terraform.io/providers/hetznercloud/hcloud/1.42.0/docs/data-sources/image](https://registry.terraform.io/providers/hetznercloud/hcloud/1.42.0/docs/data-sources/image) there should be a version 1.42.0 but the latest available release is 1.36.0.

I can reproduce this problem on my MacBook Pro. I installed the latest available version of hcloud through brew and I got 1.36.0.

The problem is, that I can't select the right image based on the architecture x86/arm. So I changed it to (but this doesn't work, at least in version 1.36):

```
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 13, in data "hcloud_image" "rocky_x86":
│   13:   with_architecture      = var.server_architecture
│ 
│ An argument named "with_architecture" is not expected here.
╵

```
Temporarily I could solve that issue with the with_selector:

```
data "hcloud_image" "rocky_x86" {
  name              = var.server_image
  with_selector     = "with_architecture=${var.server_architecture}"
  //with_architecture     = var.server_architecture --> available only from 1.38.0+
}
```

Do you know when we can expect a newer version? I saw, based on the documentation it should work from 1.38.0+.

Thanks in advance,

mtrax

**Comment by apricote** [comment]
Hey @emcdng,

there might be a misunderstanding about our projects. Our cli tool [hcloud](https://github.com/hetznercloud/cli) (this repo, latest version 1.36.0) is for use in your terminal.

Our [terraform-provider-hcloud](https://github.com/hetznercloud/terraform-provider-hcloud) is what you are using in Terraform. The latest version for this is 1.42.0. You can define the version terraform uses through [`required_providers`](https://developer.hashicorp.com/terraform/language/providers/requirements#requiring-providers):

```terraform
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.42.0"
    }
  }
}
```

Hope this will help you. I am going to close this issue, but if you still have problems please feel free to continue the discussion here.
