### ISSUE TITLE
feat: Command to list all resources

### ISSUE THREAD

**Issue by apricote** [hetznercloud/cli#545]
Introduce a new command `hcloud all list` that lists all resources in the project. This command should support label selectors. The default output would be similar to `kubectl get all`, one table per resource type:

```
$ kubectl get all -n traefik
NAME                           READY   STATUS    RESTARTS       AGE
pod/traefik-56fc75b747-fxd4k   1/1     Running   1 (6d3h ago)   6d3h

NAME              TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/traefik   LoadBalancer   10.245.208.234   10.0.0.7      80:32466/TCP,443:30059/TCP   198d

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/traefik   1/1     1            1           198d

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/traefik-56fc75b747   1         1         1       18d
replicaset.apps/traefik-5dbc8db98    0         0         0       198d
replicaset.apps/traefik-6f9987db55   0         0         0       116d
```

Open questions:

- How do we implement the `-o=columns=` and `-o=json` flags from the usual `list` command?

**Comment by stroebitzer** [comment]
I would need this also, additonally I would like to filter the resources by the API token name with which the resources have been created.

**Comment by pauhull** [comment]
Implemented in #580

**Comment by stroebitzer** [comment]
As far as I got it the API-token name is not included in the provided info. Do you intend adding this info?

**Comment by pauhull** [comment]
Unfortunately, we can only implement features supported by the Hetzner Cloud Public API (https://docs.hetzner.cloud/).
API tokens are not included in the Public API. It also does not expose who created which resource.

However, you can find this information on the activities page in the Cloud Console: https://console.hetzner.cloud/activities

I have added a vote for this feature to our internal feedback tracker.

**Comment by stroebitzer** [comment]
thx for your response. 

to give you some context about the reason why we are interested in those features. Maybe there is also a better way for supporting our situation. We are doing trainings on your VMs, everything has to be done in an automated way, so no UI involved on setup and teardown.

The easiest for us would be creation and deletion of the training projects (and all its resources), but this is not supported AFAIK

So keeping the project and doing deletion of resources identified by the API token name would my second choice TBH  :)

**Comment by apricote** [comment]
You can try to use labels for this if you control the creation of the resources, then you can use `hcloud all list -l training=2023-workshop-1` to list the resources. But this wont work if hand out the API Tokens to the training participants.

I have added a +1 on the "Public API for Creating&Deleting Projects" issue on our internal feedback tracker.
