### ISSUE TITLE
Consider asking for confirmation when deleting resources

### ISSUE THREAD

**Issue by thcyron** [hetznercloud/cli#57]
* `server delete`
* `floating-ip delete`
* `image delete`
* `ssh-key delete`

**Comment by JochenABC** [comment]
Maybe list the resource you are deleting (like <list> command output) first and then ask for confirmation?

Add a flag `-y (--yes)` to skip asking for confirmation and assume yes.

**Comment by thcyron** [comment]
Now that it‘s possible to protect resources from accidental deletion on API level, I consider this to no longer be necessary.

**Comment by perlun** [comment]
@thcyron As a fairly new user of `hcloud` and the Hetzner cloud, I think this could be reopened. Consider this:

```shell
$ hcloud server delete some-server
```

Even if the server is powered on, the API & CLI will happily delete this server without further notice. I think this is a bit overly zealous. Especially if you have done this previously in the same terminal and just press "Up" arrow and Enter without thinking, it can be quite fatal... :sweat_smile: 

We could consider doing what Docker Machine does: prompt by default:

```
$ docker-machine rm foo
About to remove foo
WARNING: This action will delete both local reference and remote instance.
Are you sure? (y/n): ^C
```

...and if `-f` or `-y` is specified, remove the machine without further ado:

```
$ docker-machine rm -f foo
About to remove foo
WARNING: This action will delete both local reference and remote instance.
Error removing host "foo": Docker machine "foo" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
Can't remove "foo"
```

I think an `-f` parameter would make most sense in our case. How about this: if the machine is _powered off_, no prompting/safety belt, but if the machine is running, ask for confirmation before removal (unless `-f` is specified)? :thinking:
