### ISSUE TITLE
hcloud: unable to authenticate (unauthorized)

### ISSUE THREAD

**Issue by marcinhlybin** [hetznercloud/cli#586]
I have troubles authorizing:

```
$ hcloud context create Marcin
Token: 
Context Marcin created and activated
$ hcloud server-type list
hcloud: unable to authenticate (unauthorized)
```

However, when I take token from `~/.config/hcloud/cli.toml` and run curl it works perfectly fine.

```
$ curl -Ss -H 'Authorization: Bearer __MY_64CHAR_TOKEN_HERE __' https://api.hetzner.cloud/v1/server_types | jq '[.server_types[].id] | length'
20
```

It would also be nice to see at least asterisks when pasting the key into input.

Also debug or verbose option would be nice to actually see what is happening under the hood and what key has been used.

MacOS 14.0
`hcloud` installed with `brew`

**Comment by pauhull** [comment]
Did you set the ``HCLOUD_TOKEN`` environment variable? It overrides the currently active context. Try running ``HCLOUD_TOKEN=<your token> hcloud server-type list``.
If that still doesn't work, try setting``HCLOUD_DEBUG=1`` and post the results here.
