### ISSUE TITLE
JSON equivalent for tabular view?

### ISSUE THREAD

**Issue by deliciouslytyped** [hetznercloud/cli#595]
When selecting output modes, is it possible / could it be possible to get JSON for selected columns?

Currently -o json and -o columns=... have orthogonal behavior, where json output just seems to dump whatever internal representation it has for the given objects, because a bunch more information is dumped sometimes than what is shown in the tabular view.
This is fine, and can be handled with jq, it might just allow slightly less scripting code.

**Comment by pauhull** [comment]
IMO this is not needed because you are most likely going to process the JSON output with a tool like jq anyway. I don't think this feature justifies the internal changes necessary (as we currently just dump the API JSON response). It might be worth getting a third opinion on this though.

**Comment by jooola** [comment]
I recommend using jq to process the json output. Adding our own JSON filtering tool is a lot of work, while the features already exists in jq/yq.

Closing as "Not Planned".
