### ISSUE TITLE
Option to disable wait for apply_firewall

### ISSUE THREAD

**Issue by simonostendorf** [hetznercloud/cli#613]
I think it would be nice to have a command flag that disables the wait for `apply_firewall`.

I have a script that uses the hcloud cli to adjust my firewall rules if a new node joins my cluster. The script should not wait that the new rules are applied to each cluster node because the label selector takes care of that.

**Comment by pauhull** [comment]
Would it not be possible to run the command in the background (using `&`)?

**Comment by simonostendorf** [comment]
> Would it not be possible to run the command in the background (using `&`)?

Works for now. Closing the issue.
