### ISSUE TITLE
ci: update version number string with release please

### ISSUE THREAD

**Issue by pauhull** [hetznercloud/cli#636]
At the moment, the version number string in `internal/version/version.go` is updated via compiler flags during the CI build. This should be changed so that Release Please updates this string for each version. This would make `hcloud version` return the correct version number instead of `Unknown` when it's installed with `go install`.

This is also already done in other projects, see https://github.com/hetznercloud/hcloud-go/blob/main/hcloud/hcloud.go#L5

**Comment by jooola** [comment]
Ideally, we also want to make a different between released version (CI build for tags), snapshots (CI build on the main branch) and dev version (e2e tests or unofficial install). This will improve our user agent based stats.

Here is an example:

https://github.com/hetznercloud/packer-plugin-hcloud/blob/8a95e8f92abb326cddada38da8472bb7425e9b0e/version/version.go#L9-L17

https://github.com/hetznercloud/packer-plugin-hcloud/blob/8a95e8f92abb326cddada38da8472bb7425e9b0e/.goreleaser.yml#L17-L18
