### ISSUE TITLE
fix: Allow multiple --type flags for metrics commands

### ISSUE THREAD

**Issue by apricote** [hetznercloud/cli#642]
When getting the metrics for Load Balancers and servers, the API allows the user to set multiple metrics types (`cpu`, `disk`, `network` for servers). The CLI currently only reads from the last specified `--type` flag. It would be nice if we used a `StringSlice` instead.

Current behaviour:

```shell
$ hcloud server metrics home-cloud-v3-l86p8-5vcvb --type cpu --type disk
Server: home-cloud-v3-l86p8-5vcvb 	 Metric: disk.0.bandwidth.read 	 Start: 2023-12-15 11:53:25 +0100 CET 	 End: 2023-12-15 12:23:25 +0100 CET
<graph removed>

Server: home-cloud-v3-l86p8-5vcvb 	 Metric: disk.0.bandwidth.write 	 Start: 2023-12-15 11:53:25 +0100 CET 	 End: 2023-12-15 12:23:25 +0100 CET
<graph removed>

Server: home-cloud-v3-l86p8-5vcvb 	 Metric: disk.0.iops.read 	 Start: 2023-12-15 11:53:25 +0100 CET 	 End: 2023-12-15 12:23:25 +0100 CET
<graph removed>

Server: home-cloud-v3-l86p8-5vcvb 	 Metric: disk.0.iops.write 	 Start: 2023-12-15 11:53:25 +0100 CET 	 End: 2023-12-15 12:23:25 +0100 CET
<graph removed>

``` 

As a workaround, it is currently possible to get back multiple types by concatenating them yourself with `,`: `--type cpu,disk`

**Comment by pauhull** [comment]
The Load Balancer metrics command had the same issue. Fixed in #649
