### ISSUE TITLE
New Feature: Unassign/Assign alias IP to server

### ISSUE THREAD

**Issue by gociii** [hetznercloud/cli#643]
Apologies if this isn't the right place. Would be great to have the functionality via hcloud-cli to unassign/assign alias ip to achieve the same functionality as is available in the management console. I understand that in addition to the actual 'Edit Alias IP' a seperate command will need to be run seperately (not part of the implementation) on the server itself after the Alias IP config is updated.

**Comment by pauhull** [comment]
Does `hcloud server change-alias-ips` not work for you? What additional functionality would you like to see added?

**Comment by gociii** [comment]
@pauhull - thanks, **just what I needed.** I didn't find it due to not being documented or not easy to find and also I was trying to look for such functionality under network rather than server. :)

Usage:

#To remove alias:
hcloud server change-alias-ips -n _NetworkName_ _ServerName_ --clear

#To assign alias:
hcloud server change-alias-ips -n  -n _NetworkName_ _ServerName_--alias-ips _ipAddress_
