### ISSUE TITLE
json output format should NOT output progress

### ISSUE THREAD

**Issue by LarsKumbier** [hetznercloud/cli#644]
`hcloud server request-console <server> -o json` now outputs not only json, but also the progress on the STDERR channel:

```
$ hcloud server request-console <server> -o json
1.1s [===================================] 100.00%
{
  "wss_url": "wss://web-console.hetzner.cloud/?server_id=<server_id>\u0026token=<token>",
  "password": "<password>"
}
```

If json is requested, only json should be in the output. Maybe add an optional `--progress`, if that feature should still be present.

Issue was introduced with hcloud v1.41.
last known good is hcloud v1.40.

**Comment by pauhull** [comment]
This is intentional. Because the progress is printed in stderr, you can handle it separately. For example, this is how you would hide it entirely:
```sh
server request-console <server> -o json 2>/dev/null
```
I don't think an extra flag for that would make sense.

**Comment by jooola** [comment]
I think it's worth adding some details about what is printed to stdout and stderr to the documentation/help page/manpage.

**Comment by LarsKumbier** [comment]
> This is intentional. Because the progress is printed in stderr, you can handle it separately. For example, this is how you would hide it entirely:

That's how I solved it for now, but I also never saw a solution like that.
I'd rather see a commandline flag instead.

**Comment by itg-dave** [comment]
> > This is intentional. Because the progress is printed in stderr, you can handle it separately. For example, this is how you would hide it entirely:
> > server request-console  -o json 2>/dev/null
> > I don't think an extra flag for that would make sense.
> 
> This doesn't make sense IMHO. If you provide JSON output, the output should be valid JSON and nothing else (p.e. kubectl -o yaml). This is not the usual way to provide this kind of feature. This breaks tools like `jq` which normally would be piped without the need to redirect stderr to /dev/null...
> 
> I can only speak for myself but this is the first application where I am forced to do it this way.

Another solution could be quiet-flag (like `curl -s`). If this is passed, we can ensure, that script-friendly output is generated.

**Comment by pauhull** [comment]
> > This is intentional. Because the progress is printed in stderr, you can handle it separately. For example, this is how you would hide it entirely:
> > server request-console  -o json 2>/dev/null
> > I don't think an extra flag for that would make sense.
> 
> This doesn't make sense IMHO. If you provide JSON output, the output should be valid JSON and nothing else (p.e. kubectl -o yaml). This is not the usual way to provide this kind of feature. This breaks tools like `jq` which normally would be piped without the need to redirect stderr to /dev/null...
> 
> I can only speak for myself but this is the first application where I am forced to do it this way.

It doesn't break jq. A pipe only forwards stdout by default, we considered that when we made the change.
Only problem I see so far is that you can't distinguish errors (which are printed to stderr too) from the progress bar output. So I think a ``--quiet` (opt-out) or ``--progress`` (opt-in) could be useful indeed.

**Comment by LarsKumbier** [comment]
You're completely right; turns out it was a completely separate issue. Should I leave the issue open as a feature request nonetheless?

**Comment by itg-dave** [comment]
> > > This is intentional. Because the progress is printed in stderr, you can handle it separately. For example, this is how you would hide it entirely:
> > > server request-console  -o json 2>/dev/null
> > > I don't think an extra flag for that would make sense.
> > 
> > 
> > This doesn't make sense IMHO. If you provide JSON output, the output should be valid JSON and nothing else (p.e. kubectl -o yaml). This is not the usual way to provide this kind of feature. This breaks tools like `jq` which normally would be piped without the need to redirect stderr to /dev/null...
> > I can only speak for myself but this is the first application where I am forced to do it this way.
> 
> It doesn't break jq. A pipe only forwards stdout by default, we considered that when we made the change. Only problem I see so far is that you can't distinguish errors (which are printed to stderr too) from the progress bar output. So I think a `--quiet` (opt-out) or `--progress` (opt-in) could be useful indeed.

Thanks for the clarification, i corrected my comment above. And thank you for considering this!

**Comment by pauhull** [comment]
Yes, I think the concern that you can't (easily) get error messages while ignoring stderr is still valid, so a ``--quiet`` flag is still useful IMO. Thanks for bringing this up for discussion 🙂

**Comment by Srakbi** [comment]
> `hcloud server request-console <server> -o json` now outputs not only json, but also the progress on the STDERR channel:
> 
> ```
> $ hcloud server request-console <server> -o json
> 1.1s [===================================] 100.00%
> {
>   "wss_url": "wss://web-console.hetzner.cloud/?server_id=<server_id>\u0026token=<token>",
>   "password": "<password>"
> }
> ```
> 
> If json is requested, only json should be in the output. Maybe add an optional `--progress`, if that feature should still be present.
> 
> Issue was introduced with hcloud v1.41.
> last known good is hcloud v1.40.

Close _ # 644

**Comment by Srakbi** [comment]
I'm sorry 😞
