### ISSUE TITLE
Introspection: Print associated project

### ISSUE THREAD

**Issue by guettli** [hetznercloud/cli#668]
### TL;DR

`hcloud project` would be nice, so that you can see which project you are currently connected to (via HCLOUD_TOKEN).

We use many hcloud projects, and sometimes it is no clear which project you are connected to.

I think about creating a [starship prompt](https://starship.rs/config/) integration, so that I see which hcloud project I am currently using.

But up to now there seems to be no way to get this information.

**Comment by pauhull** [comment]
Unfortunately the API does not offer a possibility to identify a token's parent project at the moment. However, you can probably achieve similar functionality by using contexts. You can create one context for each of your projects and then use `hcloud context active` to show your current context/project or `hcloud context use` to switch it.

**Comment by apricote** [comment]
Hey @guettli, I have added a +1 on our internal feature request board for "GET current-project" endpoint.

Closing the issue, as the CLI can only implement endpoints that are available in the API.

---

PS. I also work with different projects & tokens regularly, so I added this to my oh-my-zsh prompt:

```shell
➜  ~ hc:(personal) which hcloud_ps1
hcloud_ps1 () {
	local HCLOUD_PS1
	HCLOUD_PS1_CONTEXT="$(hcloud context active)"
	HCLOUD_PS1+="%{$fg_bold[blue]%}hc:("
	HCLOUD_PS1+="%{$fg_bold[red]%}"
	HCLOUD_PS1+="${HCLOUD_PS1_CONTEXT}"
	HCLOUD_PS1+="%{$fg_bold[blue]%})%{$reset_color%}"
	echo "${HCLOUD_PS1}"
}
➜  ~ hc:(personal)
```
