### ISSUE TITLE
mitchellh/gon is unmaintained, consider moving to bearer/gon

### ISSUE THREAD

**Issue by jooola** [hetznercloud/cli#676]
### TL;DR

We use the mitchellh/gon tool to sign the macos binaries. The project https://github.com/mitchellh/gon is unmaintained and archived. A fork was created here: https://github.com/Bearer/gon

We need to evaluate the new tool, and start using it if we consider it a "good fork".

### Expected behavior

Safely sign the mac os binaries.

### Observed behavior

Unmaintained tools are a risk.

**Comment by apricote** [comment]
We should also take a look at [`apple-codesign`](https://gregoryszorc.com/docs/apple-codesign/main/), its an open-source CLI available on Linux. This could greatly speed up the compile CI job, as the Linux runners [should be more powerful](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) by default than the macOS one we currently use.
