### ISSUE TITLE
FR: move snapshots

### ISSUE THREAD

**Issue by foertel** [hetznercloud/cli#677]
### TL;DR

Implement moving snapshots between contexts.

### Expected behavior

Snapshots can be moved via the web UI but not via the CLI. All that image / snapshot handling feels really clunky. Why can snapshots not be downloaded? Or uploaded? Or ISOs uploaded? It's really hard to deploy clusters of pre-configured nodes. If we could move snapshots we could at least place blueprints in every project.

**Comment by pauhull** [comment]
Our [Public API](https://docs.hetzner.cloud/) currently does not offer the ability to move resources between objects or to download snapshots (See https://github.com/hetznercloud/hcloud-python/issues/190). I upvoted these requests on our internal feedback tool.

[Here](https://hannes.enjoys.it/blog/2023/07/backing-up-hetzner-snapshots-locally/) you can find a workaround for downloading snapshots & backups that might work for you. You can fully automate this process using the CLI (`hcloud server create` & `hcloud server ssh`).

I'm going to close this issue now as it's not currently possible for us to implement.
