### ISSUE TITLE
Add the project name to the hcloud cmd "all"

### ISSUE THREAD

**Issue by edgecode** [hetznercloud/cli#698]
### TL;DR

The command `hcloud all list` lists all resources of the project currently selected/activ.
Howerver, it does not show any project info.

IMHO at least the _project name_ would be beneficial:
Just to make sure to be in the correct _project/context_ before copying a _resource name/Id_ and nuke-ing it away.

### Expected behavior

Project _name/Id_ (or more relevant project info) shows up in `hcloud all list`

**Comment by apricote** [comment]
Hey @edgecode,

there is currently no API endpoint to get details about the current project. We would need one to show this information. I have added a +1 to our internal feedback tracker for this request.

I personally display the active context or the token prefix in my zsh prompt: 
![screenshot-zsh-hcloud-ps1](https://github.com/hetznercloud/cli/assets/3393079/63b148a1-9693-4b78-b61a-dc3dad1e16d7)

Right now the function code is pretty much hardcoded for my theme, but you should be able to adjust the style-only lines to match your prompt:

```zsh
hcloud_ps1 () {
	if command -v hcloud > /dev/null
	then
		local HCLOUD_PS1
		HCLOUD_PS1+="%{$fg_bold[blue]%}hc:("
		HCLOUD_PS1+="%{$fg_bold[red]%}"
		if [[ -z "$HCLOUD_TOKEN" ]]
		then
			HCLOUD_PS1+="$(hcloud context active)"
		else
			HCLOUD_PS1+="$( echo $HCLOUD_TOKEN | cut -b 1-8)..."
		fi
		HCLOUD_PS1+="%{$fg_bold[blue]%})%{$reset_color%}"
		echo "${HCLOUD_PS1}"
	fi
}
```

I am going to close this issue as we can only implement what is available through the API.

**Comment by edgecode** [comment]
Sad to hear that the API does not expose the project name.
That is a bit unexpected to be honest ;-)

But hey, thanks @apricote for your quick response!
And for adding to Hetzner's internal feedback tracker.
And of course for the hint with the shell prompt; which is at least a mitigation.

best, @edgecode
