### ISSUE TITLE
hcloud context create: Add optional --token flag

### ISSUE THREAD

**Issue by thetechnick** [hetznercloud/cli#72]
When using `hcloud` in a CI environment, the user should be able to pass the token via environment variables.

**Comment by thetechnick** [comment]
The token can be piped into the `context create` command like this;
```shell
echo 'token' | hcloud context create context-name
```

**Comment by yetmorecode** [comment]
The above mentioned workaround does not work anymore..

`~/hcloud-linux-amd64-v1.3.0 $ echo "a" | ./bin/hcloud context create dummy
Token: 
hcloud: inappropriate ioctl for device
`

**Comment by isakrubin** [comment]
Reopen? This is still an issue and as @yetmorecode mentioned above, piping the token no longer works.

**Comment by thcyron** [comment]
I would suggest to use the `HCLOUD_TOKEN` environment variable in scripts as described in the [README](https://github.com/hetznercloud/cli#configure-hcloud-using-environment-variables).

**Comment by com2** [comment]
For those who want to know how to use this in practice, because it still asks for confirmation:

`HCLOUD_TOKEN=<api-key> hcloud context create <context-name> <<<"Y"`

**Comment by cwirz** [comment]
How can I run this in my CI job? Its saying that the context create command is an interactive one.

**Comment by aliceseaborn** [comment]
> How can I run this in my CI job? Its saying that the context create command is an interactive one.

Same issue on my end. i am trying to build a container to spin up Hetzner resources on-demand for GitLab runners. i am using podman secrets to expose the Hetzner API token within the container.
```bash
RUN --mount=type=secret,id=TF_VAR_hetzner_token \
  HCLOUD_TOKEN=$(cat /run/secrets/TF_VAR_hetzner_token) \
  && echo "${HCLOUD_TOKEN}" \
  && hcloud server list
```

But when i try to use the hcloud binary within the container build, i run into the following error:
```bash
$ podman build \
  --tag localhost/runner-on-demand:latest  \
  --secret id=TF_VAR_hetzner_token  \
  -f Containerfile
...
STEP 5/8: RUN --mount=type=secret,id=TF_VAR_hetzner_token   HCLOUD_TOKEN=$(cat /run/secrets/TF_VAR_hetzner_token)   && echo "${HCLOUD_TOKEN}"   && hcloud server list
<echos the correct hcloud token>
hcloud: no active context or token (see `hcloud context --help`)
```

i have tried the following means of securing an active context (named white-sands) for the hcloud binary:
```bash
HCLOUD_TOKEN=$(cat /run/secrets/TF_VAR_hetzner_token) hcloud context create white-sands <<<"Y"
echo "${HCLOUD_CLI_TOKEN}" | hcloud context create white-sands
```

These methods return the following output respectively:
```bash
STEP 5/8: RUN --mount=type=secret,id=TF_VAR_hetzner_token   HCLOUD_TOKEN=$(cat /run/secrets/TF_VAR_hetzner_token) hcloud context create white-sands <<<"Y"   && hcloud server list
hcloud: context create is an interactive command
STEP 5/8: RUN --mount=type=secret,id=TF_VAR_hetzner_token   export HCLOUD_CLI_TOKEN=$(cat /run/secrets/TF_VAR_hetzner_token)   && echo "${HCLOUD_CLI_TOKEN}" | hcloud context create white-sands   && hcloud server list
hcloud: context create is an interactive command
```

i am open to testing out any potential solutions or ideas, feel free to email me at seaborn@lavabit.com, will happily space-puppy for a solution to this issue 😄.

Thank you for all that you do 🙌🏼 
~seaborn
