### ISSUE TITLE
Context handling still not use friendly

### ISSUE THREAD

**Issue by JochenABC** [hetznercloud/cli#75]
Most users seem to assume that after creating a context it is automatically used.  Maybe we can satisfy this expectation? 

Even if we do not decide to auto-select recently created context we should print a message after context creation which clearly indicates what has happened:

Either
* new context created but you will need to run `hcloud context x use` to activate or
* new context created and it was automatically activated

**Comment by thcyron** [comment]
Right now, a created context is auto-activated iff it is the first context created. So when using the CLI for the first time and running `hcloud context create foo`, context foo is automatically activated.

Actually I’m not sure this is a good solution. We indeed should either *always* or *never* activate a created context.

**Comment by thcyron** [comment]
We decided to always activate the context just created.
