### ISSUE TITLE
Progress bar not shown correctly on Windows

### ISSUE THREAD

**Issue by thcyron** [hetznercloud/cli#76]
On Windows, the progress bar is only shown correctly when the prompt is slightly larger than the default size (in width). Otherwise the progress bar is printed multiple times.

![screenshot 145 eingabeaufforderung](https://user-images.githubusercontent.com/13827/35207637-5fe3fa44-ff44-11e7-8b76-39a4c22f15df.png)

**Comment by thcyron** [comment]
Also happens on macOS and is a known problem in the [uiprogress library](https://github.com/gosuri/uiprogress/issues/3) in narrow terminal windows. There is no fix.

We can either:

1. Try to fix it ourselves.
2. Look for another progress bar library which does not suffer from that problem.
3. Ditch the progress bar and simply print the percentage.

**Comment by patrickschaffrath** [comment]
Fixed with #218
