### ISSUE TITLE
Structured access to fields (JSON, Go templates)

### ISSUE THREAD

**Issue by thcyron** [hetznercloud/cli#82]
Sometimes you want to use the CLI in a shell script to get some information, but parsing the output is obviously a bad idea. We should consider adding JSON support so you can access information in a structured way.

Have a look at how `docker inspect` enables this: https://docs.docker.com/engine/reference/commandline/inspect/#extended-description

**Comment by hojerst** [comment]
isn‘t this already possible by using

hcloud -o outputformat=json -o columns=field1,field2

?

**Comment by thetechnick** [comment]
@hojerst This is not yet implemented `-o` only supports `noheader` and `columns=` but not json output or templating.

We are still discussing how we want to implement this functions and what we want to support.

**Comment by mblaschke** [comment]
Any news about this feature?
Parsing strings doesn't feel good. Would be nice to get a valid JSON structure which can be parsed.

**Comment by thcyron** [comment]
I’d suggest you use [our API](https://docs.hetzner.cloud/) directly if you need JSON output.

**Comment by mblaschke** [comment]
So i have to write my own cli client to get the json output?

I like the `docker` and `kubectl` approach where you can get the json output directly and also the readable formats. Should be not too difficult to implement this feature.

This feature would allow easy and safe processing in other scripting languages and just use the hcloud cli client to access the api.

**Comment by thcyron** [comment]
There’s now support for JSON and Go template output. See the readme how to use it.
