### ISSUE TITLE
running tests

### ISSUE THREAD

**Issue by asarubbo** [hetznercloud/cli#887]
This is a question more than an issue, but I can't set a proper label.

I'm maintaining hcloud-cli in gentoo.

README.md does not explain how to run tests, but digging into `.github/workflows/ci.yml` I see:

```
go test -coverpkg=./... -coverprofile=coverage.txt -v -race ./...
go test -tags e2e -coverpkg=./... -coverprofile=coverage.txt -v -race ./test/e2e
```

Both works for me but I'm wondering if there are tests in `e2e` that can be done without an HCLOUD_TOKEN.
If yes how?

Thanks

**Comment by jooola** [comment]
The e2e tests rely on the Hetzner Cloud API to run, so you will need an HCLOUD_TOKEN to run them. There is no working around this requirement.

And there should not be any unit tests inside the e2e tests.

I hope this answers your question?

**Comment by asarubbo** [comment]
Yes it does, thank you
