### ISSUE TITLE
support non-interactive input on more functions as pipe or parameter

### ISSUE THREAD

**Issue by Reiner030** [hetznercloud/cli#89]
like initial setup cannot be scripted:
````
# echo "XXXXXXXX_TOKEN_XXXXXXXX" | hcloud context create Testing
Token:
hcloud: inappropriate ioctl for device
````

**Comment by thetechnick** [comment]
Hi @Reiner030,
can you share some more background information about your setup?
With zsh on Fedora 27 this command works just fine.

Also when using the `hcloud` command in an automated environment you might want to use the `HCLOUD_TOKEN` environment variable, so you do not need to setup the context.

**Comment by thcyron** [comment]
It worked prior to v1.3.0. ddd1601f39371d546e15e6781a828bfc90a7c0fe broke it. But as @thetechnick said, using `HCLOUD_TOKEN` in scripts is the preferred way.

**Comment by yetmorecode** [comment]
Is `HCLOUD_TOKEN` documented somewhere. Could not find anything about it until I cam across this ticket. If it's not documented, would be helpful to have it mentioned in the README.

**Comment by yetmorecode** [comment]
I have a hard time automating this. I can't list servers without a context and I can't create a context without user input.

```
$ export HCLOUD_TOKEN="..."
$ ./bin/hcloud server list
hcloud: no active context (see `hcloud context --help`)
$ ./bin/hcloud context create dummy
Token: 
```

**Comment by thcyron** [comment]
I will make `HCLOUD_TOKEN` work again and document it.

**Comment by alexanderkjeldaas** [comment]
What's a working workaround for hcloud 1.3.0?

**Comment by thetechnick** [comment]
Hi @alexanderkjeldaas,
if `HCLOUD_TOKEN` is set, the current context does not matter.

**Comment by computersrmyfriends** [comment]
Any documentation available on this? It's not working

**Comment by bounmed** [comment]
is this still broken in v1.34.0 ?

This method ask for the token
`
export HCLOUD_TOKEN="cVd.."
 hcloud context create test
Token: 
`
And the pipe method not working either

**Comment by cwirz** [comment]
I also need a solution for this. Related: #72

**Comment by aliceseaborn** [comment]
^bump
Yup, still challenging to use hcloud in a CI pipeline but i understand y'all are busy. i'm just excited to use my favorite CSP throughout my cloud operations 😊

**Comment by smallstepman** [comment]
check is too restrictive, error originates here
https://github.com/hetznercloud/cli/blob/ee626221938365447e167d18763dc303f0ab77be/internal/cmd/context/create.go#L33-L35

@aliceseaborn temp fix
```yml
      - name: set context with random suffix
        run: |
          sudo apt-get install -y expect
          HCLOUD_TOKEN=${{ secrets.HETZNER_CLOUD_API }} expect <<EOF
          set timeout -1
          spawn hcloud context create your-context-$(xxd -l 8 -p /dev/urandom)
          expect "Y"
          send "Y\r"
          expect eof
          EOF
```
