### ISSUE TITLE
hcloud: server limit reached

### ISSUE THREAD

**Issue by dummys** [hetznercloud/cli#91]
Hi, when using hcloud to create a new server i get this error: "Server limit reached" Was it this ?

**Comment by thetechnick** [comment]
Hi @dummys,
we have a server limit so new customers cannot abuse our services.

Please look at this issue for more details:
https://github.com/hetznercloud/terraform-provider-hcloud/issues/16

**Comment by vott** [comment]
Hey is this documented somewhere?

**Comment by apricote** [comment]
Hey @vott, this is documented in the general FAQ: https://docs.hetzner.com/cloud/general/faq/#are-there-limits-to-the-number-of-resources-i-can-get

You can check your current limits & usage at https://console.hetzner.cloud/limits
