### ISSUE TITLE
server location / datacenter not printed in describe

### ISSUE THREAD

**Issue by elconas** [hetznercloud/cli#95]
It is not possbile to get the server location and datacenter via the CLI neither with 

```
hcloud server list
```

nor 

```
hcloud server describe xxx
```

While the API provides the information.

**Comment by thetechnick** [comment]
Hi @elconas,
thanks for your issue!

I have just pushed a PR that adds datacenter and location to the output of `hcloud server describe/list`: https://github.com/hetznercloud/cli/pull/98

**Comment by thcyron** [comment]
I merged #98 adding datacenter to `server list` and `server describe`. Closing this then.
