### ISSUE TITLE
Following the "Getting started" guide leads to error

### ISSUE THREAD

**Issue by vincentsch** [hetznercloud/cli#96]
I'm under Windows 10 using "hcloud-windows-amd64-v1.3.1.zip" release.

I followed the 3 steps from https://github.com/hetznercloud/cli#getting-started

Result: hcloud: unable to authenticate your token (unauthorized)

For some reason hcloud is not using/accepting my token.

**Comment by thcyron** [comment]
I’ve just tried it on a Windows machine and was successfully able to create a token and list server types. Please make sure you copied and pasted the token correctly. Reopen if it’s still an issue for you.
